//! Allowed Lucide-style icon keys for environment surface nav.

pub const ALLOWED_SURFACE_ICONS: &[&str] = &[
    "activity",
    "bar-chart-3",
    "bell",
    "bike",
    "book-open",
    "bookmark",
    "bot",
    "brain",
    "calendar",
    "camera",
    "car",
    "checklist",
    "clipboard",
    "cloud",
    "coffee",
    "compass",
    "database",
    "droplet",
    "file-text",
    "flag",
    "flame",
    "folder",
    "gamepad-2",
    "gem",
    "globe",
    "hash",
    "headphones",
    "heart",
    "home",
    "image",
    "layout-grid",
    "line-chart",
    "list",
    "map-pin",
    "message-circle",
    "mic",
    "moon",
    "music",
    "orbit",
    "paintbrush",
    "palette",
    "pen-line",
    "pie-chart",
    "plane",
    "radio",
    "rss",
    "settings",
    "sparkles",
    "star",
    "sun",
    "tag",
    "target",
    "train-front",
    "trophy",
    "user",
    "users",
    "video",
    "wand-sparkles",
    "zap",
];

pub fn is_valid_surface_icon(icon: &str) -> bool {
    let trimmed = icon.trim();
    !trimmed.is_empty() && ALLOWED_SURFACE_ICONS.contains(&trimmed)
}
