use std::collections::BTreeMap;

use serde::Serialize;
use serde_json::{Value, json};

use crate::id::const_name;
use crate::provenance;
use crate::registry::ContractRegistry;
use crate::spec::{OperationSpec, ParameterLocation, SchemaRef, StreamTransport};
use crate::OPENAPI_VERSION;

const ARTIFACT_HEADER: &str = "Generated by medousa-api-contract. Do not edit.";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedArtifacts {
    pub openapi_json: String,
    pub route_inventory_json: String,
    pub rust_ops: String,
    pub python_ops: String,
    pub typescript_ops: String,
    pub tauri_enum: String,
}

pub fn generate_artifacts(registry: &ContractRegistry) -> GeneratedArtifacts {
    generate_artifacts_with_catalog(registry, &BTreeMap::new())
}

pub fn generate_artifacts_with_catalog(
    registry: &ContractRegistry,
    catalog: &BTreeMap<String, Value>,
) -> GeneratedArtifacts {
    GeneratedArtifacts {
        openapi_json: generate_openapi(registry, catalog),
        route_inventory_json: generate_route_inventory(registry),
        rust_ops: generate_rust_ops(registry),
        python_ops: generate_python_ops(registry),
        typescript_ops: generate_typescript_ops(registry),
        tauri_enum: generate_tauri_enum(registry),
    }
}

pub fn generate_openapi(registry: &ContractRegistry, catalog: &BTreeMap<String, Value>) -> String {
    let mut paths = BTreeMap::new();
    let mut schemas = BTreeMap::new();
    schemas.insert("ApiErrorEnvelope".to_string(), api_error_envelope_schema());
    schemas.insert("HealthLiveness".to_string(), health_liveness_schema());
    schemas.insert("JsonRpcMessage".to_string(), json_rpc_message_schema());
    schemas.insert("ForgeStreamEvent".to_string(), forge_stream_event_schema());
    schemas.insert(
        "ForgeProjectEvent".to_string(),
        forge_project_event_schema(),
    );

    for spec in registry.operations() {
        collect_schema(&mut schemas, spec, catalog);
        let path_item = paths.entry(spec.path.clone()).or_insert_with(BTreeMap::new);
        path_item.insert(spec.method.as_str().to_ascii_lowercase(), operation_object(spec));
    }

    let doc = json!({
        "openapi": OPENAPI_VERSION,
        "info": {
            "title": "Medousa daemon API",
            "version": "v1"
        },
        "x-medousa-generated": provenance(),
        "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
        "paths": paths,
        "components": { "schemas": schemas }
    });
    pretty(&doc)
}

pub fn generate_route_inventory(registry: &ContractRegistry) -> String {
    #[derive(Serialize)]
    struct Row<'a> {
        operation_id: &'a str,
        method: &'a str,
        path: &'a str,
        feature_profile: FeatureProfileWire,
        trust_group: &'a str,
        capabilities: &'a [String],
        browser_policy: &'a str,
        body_limit: usize,
        rate_limit_class: &'a str,
        bootstrap_public: bool,
        streaming: bool,
        stream_transport: Option<&'a str>,
    }

    #[derive(Serialize)]
    #[serde(rename_all = "snake_case")]
    enum FeatureProfileWire {
        Core,
        Pairing,
        Preview,
        OptionalWorkload,
        Development,
        TestOnly,
    }

    impl From<crate::spec::FeatureProfile> for FeatureProfileWire {
        fn from(value: crate::spec::FeatureProfile) -> Self {
            match value {
                crate::spec::FeatureProfile::Core => Self::Core,
                crate::spec::FeatureProfile::Pairing => Self::Pairing,
                crate::spec::FeatureProfile::Preview => Self::Preview,
                crate::spec::FeatureProfile::OptionalWorkload => Self::OptionalWorkload,
                crate::spec::FeatureProfile::Development => Self::Development,
                crate::spec::FeatureProfile::TestOnly => Self::TestOnly,
            }
        }
    }

    let mut rows: Vec<Row<'_>> = registry
        .operations()
        .map(|spec| Row {
            operation_id: &spec.operation_id,
            method: spec.method.as_str(),
            path: &spec.path,
            feature_profile: spec.feature_profile.into(),
            trust_group: &spec.trust_group,
            capabilities: &spec.capabilities,
            browser_policy: &spec.browser_policy,
            body_limit: spec.body_limit,
            rate_limit_class: &spec.rate_limit_class,
            bootstrap_public: spec.bootstrap_public,
            streaming: spec.stream.as_ref().is_some_and(|stream| {
                stream.transport == StreamTransport::Sse
            }),
            stream_transport: spec.stream.as_ref().map(|stream| match stream.transport {
                StreamTransport::Sse => "sse",
                StreamTransport::WebSocket => "websocket",
            }),
        })
        .collect();
    rows.sort_by(|left, right| {
        left.path
            .cmp(right.path)
            .then_with(|| left.method.cmp(right.method))
    });
    let doc = json!({
        "x-medousa-generated": provenance(),
        "operations": rows
    });
    pretty(&doc)
}

pub fn generate_rust_ops(registry: &ContractRegistry) -> String {
    let mut out = String::new();
    out.push_str(&format!("// {ARTIFACT_HEADER}\n"));
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct Operation {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub method: &'static str,\n");
    out.push_str("    pub path: &'static str,\n");
    out.push_str("    pub streaming: bool,\n");
    out.push_str("}\n\n");
    let mut ops = registry.operations().collect::<Vec<_>>();
    ops.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));
    for spec in &ops {
        let name = const_name(&spec.operation_id);
        out.push_str(&format!(
            "pub const {name}: Operation = Operation {{\n    id: \"{}\",\n    method: \"{}\",\n    path: \"{}\",\n    streaming: {},\n}};\n\n",
            spec.operation_id,
            spec.method.as_str(),
            spec.path.replace('\\', "\\\\").replace('"', "\\\""),
            spec.stream.as_ref().is_some_and(|stream| {
                stream.transport == StreamTransport::Sse
            }),
        ));
    }
    out.push_str("pub static ALL: &[Operation] = &[\n");
    for spec in &ops {
        out.push_str(&format!("    {},\n", const_name(&spec.operation_id)));
    }
    out.push_str("];\n\n");
    out.push_str("pub fn by_id(id: &str) -> Option<&'static Operation> {\n");
    out.push_str("    ALL.iter().find(|operation| operation.id == id)\n");
    out.push_str("}\n");
    out
}

pub fn generate_python_ops(registry: &ContractRegistry) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {ARTIFACT_HEADER}\n"));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import NamedTuple\n\n\n");
    out.push_str("class Operation(NamedTuple):\n");
    out.push_str("    id: str\n");
    out.push_str("    method: str\n");
    out.push_str("    path: str\n");
    out.push_str("    streaming: bool\n\n\n");
    let mut ops = registry.operations().collect::<Vec<_>>();
    ops.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));
    out.push_str("OPERATIONS: dict[str, Operation] = {\n");
    for spec in &ops {
        out.push_str(&format!(
            "    \"{}\": Operation(\"{}\", \"{}\", \"{}\", {}),\n",
            spec.operation_id,
            spec.operation_id,
            spec.method.as_str(),
            spec.path.replace('\\', "\\\\").replace('"', "\\\""),
            if spec
                .stream
                .as_ref()
                .is_some_and(|stream| stream.transport == StreamTransport::Sse)
            {
                "True"
            } else {
                "False"
            },
        ));
    }
    out.push_str("}\n\n\n");
    out.push_str("def by_id(operation_id: str) -> Operation:\n");
    out.push_str("    return OPERATIONS[operation_id]\n");
    out
}

pub fn generate_typescript_ops(registry: &ContractRegistry) -> String {
    let mut out = String::new();
    out.push_str(&format!("// {ARTIFACT_HEADER}\n"));
    out.push_str("export type HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\" | \"HEAD\" | \"OPTIONS\";\n\n");
    out.push_str("export interface Operation {\n");
    out.push_str("  readonly id: string;\n");
    out.push_str("  readonly method: HttpMethod;\n");
    out.push_str("  readonly path: string;\n");
    out.push_str("  readonly streaming: boolean;\n");
    out.push_str("}\n\n");
    let mut ops = registry.operations().collect::<Vec<_>>();
    ops.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));
    out.push_str("export const OPERATIONS = {\n");
    for spec in &ops {
        out.push_str(&format!(
            "  \"{}\": {{ id: \"{}\", method: \"{}\", path: \"{}\", streaming: {} }},\n",
            spec.operation_id,
            spec.operation_id,
            spec.method.as_str(),
            spec.path.replace('\\', "\\\\").replace('"', "\\\""),
            spec.stream.as_ref().is_some_and(|stream| {
                stream.transport == StreamTransport::Sse
            }),
        ));
    }
    out.push_str("} as const satisfies Record<string, Operation>;\n\n");
    out.push_str("export type OperationId = keyof typeof OPERATIONS;\n\n");
    out.push_str("export function operation(id: OperationId): Operation {\n");
    out.push_str("  return OPERATIONS[id];\n");
    out.push_str("}\n");
    out
}

pub fn generate_tauri_enum(registry: &ContractRegistry) -> String {
    let mut out = String::new();
    out.push_str(&format!("// {ARTIFACT_HEADER}\n"));
    out.push_str("#![allow(dead_code)]\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum DaemonOperation {\n");
    let mut ops = registry.operations().collect::<Vec<_>>();
    ops.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));
    for spec in &ops {
        out.push_str(&format!(
            "    #[serde(rename = \"{}\")]\n    {},\n",
            spec.operation_id,
            rust_enum_ident(&spec.operation_id),
        ));
    }
    out.push_str("}\n\nimpl DaemonOperation {\n");
    out.push_str("    pub fn id(self) -> &'static str {\n        match self {\n");
    for spec in &ops {
        out.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            rust_enum_ident(&spec.operation_id),
            spec.operation_id
        ));
    }
    out.push_str("        }\n    }\n}\n");
    out
}

fn rust_enum_ident(operation_id: &str) -> String {
    operation_id
        .split(|c: char| !(c.is_ascii_alphanumeric()))
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn operation_object(spec: &OperationSpec) -> Value {
    let mut parameters = Vec::new();
    for parameter in &spec.parameters {
        parameters.push(json!({
            "name": parameter.name,
            "in": match parameter.location {
                ParameterLocation::Path => "path",
                ParameterLocation::Query => "query",
                ParameterLocation::Header => "header",
                ParameterLocation::Cookie => "cookie",
            },
            "required": parameter.required,
            "schema": schema_object(&parameter.schema),
        }));
    }
    let mut responses = BTreeMap::new();
    for response in &spec.responses {
        responses.insert(
            response.status.to_string(),
            json!({
                "description": spec.operation_id,
                "content": {
                    response.media_type.clone(): {
                        "schema": schema_object(&response.schema)
                    }
                }
            }),
        );
    }
    let mut op = json!({
        "operationId": spec.operation_id,
        "x-medousa-policy": {
            "trust_group": spec.trust_group,
            "credential_scheme": spec.credential_scheme,
            "capabilities": spec.capabilities,
            "browser_policy": spec.browser_policy,
            "body_limit": spec.body_limit,
            "rate_limit_class": spec.rate_limit_class,
            "bootstrap_public": spec.bootstrap_public,
            "feature_profile": spec.feature_profile,
        },
        "parameters": parameters,
        "responses": responses,
    });
    if let Some(body) = &spec.request_body {
        op["requestBody"] = json!({
            "required": body.required,
            "content": {
                body.media_type.clone(): { "schema": schema_object(&body.schema) }
            }
        });
    }
    if let Some(stream) = &spec.stream {
        op["x-medousa-stream"] = json!({
            "transport": match stream.transport {
                StreamTransport::Sse => "sse",
                StreamTransport::WebSocket => "websocket",
            },
            "itemSchema": schema_object(&stream.item_schema),
            "lastEventId": stream.last_event_id,
            "heartbeatComments": stream.heartbeat_comments,
            "replay": stream.replay,
        });
        if stream.transport == StreamTransport::Sse {
            op["responses"]["200"]["content"] = json!({
                "text/event-stream": {
                    "schema": { "type": "string" },
                    "itemSchema": schema_object(&stream.item_schema)
                }
            });
        }
    }
    op
}

fn schema_object(schema: &SchemaRef) -> Value {
    if schema.opaque {
        json!({ "description": schema.name, "x-medousa-opaque": true })
    } else if schema.name == "string" {
        json!({ "type": "string" })
    } else {
        json!({ "$ref": format!("#/components/schemas/{}", schema.name) })
    }
}

fn collect_schema(
    schemas: &mut BTreeMap<String, Value>,
    spec: &OperationSpec,
    catalog: &BTreeMap<String, Value>,
) {
    let mut refs = Vec::new();
    if let Some(body) = &spec.request_body {
        refs.push(&body.schema);
    }
    for response in &spec.responses {
        refs.push(&response.schema);
    }
    if let Some(stream) = &spec.stream {
        refs.push(&stream.item_schema);
    }
    for schema in refs {
        if schema.opaque || schema.name == "string" || schemas.contains_key(&schema.name) {
            continue;
        }
        if let Some(root) = catalog.get(&schema.name) {
            ingest_schemars(&schema.name, root, schemas);
        } else {
            schemas.insert(
                schema.name.clone(),
                json!({
                    "type": "object",
                    "description": format!("Wire type {}", schema.name),
                    "x-medousa-unresolved": true
                }),
            );
        }
    }
}

fn ingest_schemars(name: &str, root: &Value, schemas: &mut BTreeMap<String, Value>) {
    let rewritten = rewrite_definition_refs(root);
    if let Some(definitions) = rewritten.get("definitions").and_then(Value::as_object) {
        for (def_name, definition) in definitions {
            schemas
                .entry(def_name.clone())
                .or_insert_with(|| strip_schema_meta(definition));
        }
    }
    schemas
        .entry(name.to_string())
        .or_insert_with(|| strip_schema_meta(&rewritten));
}

fn rewrite_definition_refs(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut out = serde_json::Map::new();
            for (key, child) in map {
                if key == "$ref"
                    && let Some(reference) = child.as_str()
                {
                    out.insert(
                        key.clone(),
                        Value::String(reference.replace("#/definitions/", "#/components/schemas/")),
                    );
                    continue;
                }
                out.insert(key.clone(), rewrite_definition_refs(child));
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(rewrite_definition_refs).collect()),
        other => other.clone(),
    }
}

fn strip_schema_meta(value: &Value) -> Value {
    let mut cloned = value.clone();
    if let Some(object) = cloned.as_object_mut() {
        object.remove("$schema");
        object.remove("definitions");
    }
    cloned
}

fn api_error_envelope_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["schema_version", "code", "message", "request_id", "details"],
        "properties": {
            "schema_version": { "type": "integer", "const": 1 },
            "code": { "type": "string" },
            "message": { "type": "string" },
            "request_id": { "type": "string" },
            "details": { "type": "object" },
            "retry_after_ms": { "type": ["integer", "null"] }
        }
    })
}

fn health_liveness_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["status", "apiVersion"],
        "properties": {
            "status": { "type": "string", "const": "ok" },
            "apiVersion": { "type": "string", "const": "v1" }
        }
    })
}

fn json_rpc_message_schema() -> Value {
    json!({
        "type": "object",
        "description": "JSON-RPC or LSP message exchanged over a WebSocket upgrade",
        "additionalProperties": true
    })
}

fn forge_stream_event_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["work_id", "state", "event_kind", "updated_at"],
        "properties": {
            "work_id": { "type": "string" },
            "state": { "type": "string" },
            "event_kind": { "type": "string" },
            "updated_at": { "type": "string", "format": "date-time" }
        }
    })
}

fn forge_project_event_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["seq", "work_id", "kind", "updated_at"],
        "properties": {
            "seq": { "type": "integer" },
            "work_id": { "type": "string" },
            "kind": { "type": "string" },
            "path": { "type": ["string", "null"] },
            "old_path": { "type": ["string", "null"] },
            "digest": { "type": ["string", "null"] },
            "updated_at": { "type": "string", "format": "date-time" }
        }
    })
}

fn pretty(value: &Value) -> String {
    let mut text = serde_json::to_string_pretty(value).expect("json");
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::ContractRegistry;
    use crate::spec::{
        Audience, FeatureProfile, HttpMethod, OperationSpec, ResponseSpec, SchemaRef, Stability,
        StreamSpec,
    };

    fn liveness() -> OperationSpec {
        OperationSpec {
            operation_id: "liveness.get".into(),
            stability: Stability::Stable,
            feature_profile: FeatureProfile::Core,
            audience: Audience::PublicSdk,
            method: HttpMethod::Get,
            path: "/health".into(),
            parameters: Vec::new(),
            request_body: None,
            responses: vec![ResponseSpec {
                status: 200,
                media_type: "application/json".into(),
                schema: SchemaRef::named("HealthLiveness"),
            }],
            error_codes: vec!["internal_failure".into()],
            trust_group: "liveness".into(),
            credential_scheme: "none".into(),
            capabilities: Vec::new(),
            browser_policy: "public".into(),
            body_limit: 1024,
            rate_limit_class: "liveness".into(),
            bootstrap_public: true,
            stream: None,
            deprecation: None,
        }
    }

    fn stream_op() -> OperationSpec {
        let mut spec = liveness();
        spec.operation_id = "interactive.stream.get".into();
        spec.path = "/v1/interactive/turn/{id}/stream".into();
        spec.bootstrap_public = false;
        spec.trust_group = "portal".into();
        spec.capabilities = vec!["workshop.read".into()];
        spec.rate_limit_class = "stream".into();
        spec.stream = Some(StreamSpec::json_events(SchemaRef::named(
            "TurnStreamEnvelopeV2",
        )));
        spec.responses = vec![ResponseSpec {
            status: 200,
            media_type: "text/event-stream".into(),
            schema: SchemaRef::named("TurnStreamEnvelopeV2"),
        }];
        spec.with_path_parameters()
    }

    #[test]
    fn generation_is_byte_deterministic() {
        let mut registry = ContractRegistry::new();
        registry.register(liveness()).unwrap();
        registry.register(stream_op()).unwrap();
        let first = generate_artifacts(&registry);
        let second = generate_artifacts(&registry);
        assert_eq!(first.openapi_json, second.openapi_json);
        assert_eq!(first.route_inventory_json, second.route_inventory_json);
        assert!(first.openapi_json.contains("\"openapi\": \"3.2.0\""));
        assert!(first.openapi_json.contains("x-medousa-stream"));
        assert!(first.openapi_json.contains("itemSchema"));
        assert!(!first.rust_ops.contains("SSE"));
    }

    #[test]
    fn generate_twice_into_temp_dirs_is_byte_identical() {
        let mut registry = ContractRegistry::new();
        registry.register(liveness()).unwrap();
        let first = generate_artifacts(&registry);
        let second = generate_artifacts(&registry);
        let left = std::env::temp_dir().join("medousa-contract-a");
        let right = std::env::temp_dir().join("medousa-contract-b");
        std::fs::create_dir_all(&left).unwrap();
        std::fs::create_dir_all(&right).unwrap();
        std::fs::write(left.join("openapi.json"), &first.openapi_json).unwrap();
        std::fs::write(right.join("openapi.json"), &second.openapi_json).unwrap();
        assert_eq!(
            std::fs::read(left.join("openapi.json")).unwrap(),
            std::fs::read(right.join("openapi.json")).unwrap()
        );
    }

    fn websocket_op() -> OperationSpec {
        let mut spec = liveness();
        spec.operation_id = "code.lsp.get".into();
        spec.path = "/v1/code/lsp".into();
        spec.bootstrap_public = false;
        spec.trust_group = "portal".into();
        spec.capabilities = vec!["workshop.read".into()];
        spec.stream = Some(StreamSpec::websocket(SchemaRef::named("JsonRpcMessage")));
        spec.responses = vec![ResponseSpec {
            status: 200,
            media_type: "application/json".into(),
            schema: SchemaRef::named("JsonRpcMessage"),
        }];
        spec
    }

    #[test]
    fn websocket_openapi_keeps_json_and_is_not_sse() {
        let mut registry = ContractRegistry::new();
        registry.register(websocket_op()).unwrap();
        let artifacts = generate_artifacts(&registry);
        assert!(artifacts.openapi_json.contains("\"transport\": \"websocket\""));
        assert!(!artifacts.openapi_json.contains("text/event-stream"));
        assert!(artifacts.route_inventory_json.contains("\"streaming\": false"));
        assert!(artifacts.route_inventory_json.contains("\"stream_transport\": \"websocket\""));
        assert!(artifacts.rust_ops.contains("streaming: false"));
    }

    #[test]
    fn catalog_named_schema_is_ingested() {
        let mut spec = liveness();
        spec.responses[0].schema = SchemaRef::named("HealthResponse");
        let mut registry = ContractRegistry::new();
        registry.register(spec).unwrap();
        let mut catalog = BTreeMap::new();
        catalog.insert(
            "HealthResponse".into(),
            json!({
                "type": "object",
                "properties": { "ok": { "type": "boolean" } }
            }),
        );
        let openapi = generate_openapi(&registry, &catalog);
        assert!(openapi.contains("\"HealthResponse\""));
        assert!(openapi.contains("\"ok\""));
        assert!(!openapi.contains("x-medousa-unresolved"));
        let missing = generate_openapi(&registry, &BTreeMap::new());
        assert!(missing.contains("x-medousa-unresolved"));
    }
}
