/**
 * UI registration for Liquid archetypes. Descriptors live in index.ts;
 * this module maps ids to Svelte bodies and must not be imported from the
 * parse/sanitize path.
 */
import "$lib/liquid/styles/liquidOverflow.css";
import { registerComponent } from "$lib/liquid/render/componentRegistry";
import { button } from "./atoms/button/button";
import { chip } from "./atoms/chip/chip";
import { media } from "./atoms/media/media";
import { metadata } from "./atoms/metadata/metadata";
import { prose } from "./atoms/prose/prose";
import { statusPill } from "./atoms/status_pill/statusPill";
import { whisper } from "./atoms/whisper/whisper";
import { stack } from "./layout/stack/stack";
import { accordion } from "./molecules/accordion/accordion";
import { actionRow } from "./molecules/action_row/actionRow";
import { block } from "./molecules/block/block";
import { callout } from "./molecules/callout/callout";
import { card } from "./molecules/card/card";
import { carousel } from "./molecules/carousel/carousel";
import { chipGroup } from "./molecules/chip_group/chipGroup";
import { cite } from "./molecules/cite/cite";
import { code } from "./molecules/code/code";
import { observability } from "./molecules/observability/observability";
import { section } from "./molecules/section/section";
import { steps } from "./molecules/steps/steps";
import { tabs } from "./molecules/tabs/tabs";
import { tree } from "./molecules/tree/tree";
import { brief } from "./organisms/brief/brief";
import { chart } from "./organisms/chart/chart";
import { compare } from "./organisms/compare/compare";
import { dashboard } from "./organisms/dashboard/dashboard";
import { decision } from "./organisms/decision/decision";
import { document } from "./organisms/document/document";
import { feed } from "./organisms/feed/feed";
import { plan } from "./organisms/plan/plan";
import { report } from "./organisms/report/report";
import { shortlist } from "./organisms/shortlist/shortlist";
import { slides } from "./organisms/slides/slides";
import { timeline } from "./organisms/timeline/timeline";
import { chatMedia } from "./shell/chat_media/chatMedia";
import { presentation } from "./shell/presentation/presentation";
import { thinking } from "./shell/thinking/thinking";
import { toolTrace } from "./shell/tool_trace/toolTrace";
import Button from "./atoms/button/Button.svelte";
import Chip from "./atoms/chip/Chip.svelte";
import Media from "./atoms/media/Media.svelte";
import Metadata from "./atoms/metadata/Metadata.svelte";
import Prose from "./atoms/prose/Prose.svelte";
import StatusPill from "./atoms/status_pill/StatusPill.svelte";
import Whisper from "./atoms/whisper/Whisper.svelte";
import Stack from "./layout/stack/Stack.svelte";
import Accordion from "./molecules/accordion/Accordion.svelte";
import ActionRow from "./molecules/action_row/ActionRow.svelte";
import Block from "./molecules/block/Block.svelte";
import Callout from "./molecules/callout/Callout.svelte";
import Card from "./molecules/card/Card.svelte";
import Carousel from "./molecules/carousel/Carousel.svelte";
import ChipGroup from "./molecules/chip_group/ChipGroup.svelte";
import Cite from "./molecules/cite/Cite.svelte";
import Code from "./molecules/code/Code.svelte";
import Observability from "./molecules/observability/Observability.svelte";
import Section from "./molecules/section/Section.svelte";
import Steps from "./molecules/steps/Steps.svelte";
import Tabs from "./molecules/tabs/Tabs.svelte";
import Tree from "./molecules/tree/Tree.svelte";
import Brief from "./organisms/brief/Brief.svelte";
import Chart from "./organisms/chart/Chart.svelte";
import Compare from "./organisms/compare/Compare.svelte";
import Dashboard from "./organisms/dashboard/Dashboard.svelte";
import Decision from "./organisms/decision/Decision.svelte";
import Document from "./organisms/document/Document.svelte";
import Feed from "./organisms/feed/Feed.svelte";
import Plan from "./organisms/plan/Plan.svelte";
import Report from "./organisms/report/Report.svelte";
import Shortlist from "./organisms/shortlist/Shortlist.svelte";
import Slides from "./organisms/slides/Slides.svelte";
import Timeline from "./organisms/timeline/Timeline.svelte";
import ChatMedia from "./shell/chat_media/ChatMedia.svelte";
import Presentation from "./shell/presentation/Presentation.svelte";
import Thinking from "./shell/thinking/Thinking.svelte";
import ToolTrace from "./shell/tool_trace/ToolTrace.svelte";

registerComponent(button.id, Button);
registerComponent(chip.id, Chip);
registerComponent(media.id, Media);
registerComponent(metadata.id, Metadata);
registerComponent(prose.id, Prose);
registerComponent(statusPill.id, StatusPill);
registerComponent(whisper.id, Whisper);
registerComponent(stack.id, Stack);
registerComponent(accordion.id, Accordion);
registerComponent(actionRow.id, ActionRow);
registerComponent(block.id, Block);
registerComponent(callout.id, Callout);
registerComponent(card.id, Card);
registerComponent(carousel.id, Carousel);
registerComponent(chipGroup.id, ChipGroup);
registerComponent(cite.id, Cite);
registerComponent(code.id, Code);
registerComponent(observability.id, Observability);
registerComponent(section.id, Section);
registerComponent(steps.id, Steps);
registerComponent(tabs.id, Tabs);
registerComponent(tree.id, Tree);
registerComponent(brief.id, Brief);
registerComponent(chart.id, Chart);
registerComponent(compare.id, Compare);
registerComponent(dashboard.id, Dashboard);
registerComponent(decision.id, Decision);
registerComponent(document.id, Document);
registerComponent(feed.id, Feed);
registerComponent(plan.id, Plan);
registerComponent(report.id, Report);
registerComponent(shortlist.id, Shortlist);
registerComponent(slides.id, Slides);
registerComponent(timeline.id, Timeline);
registerComponent(chatMedia.id, ChatMedia);
registerComponent(presentation.id, Presentation);
registerComponent(thinking.id, Thinking);
registerComponent(toolTrace.id, ToolTrace);
