/** Curated Lucide kebab-case icons allowed on environment surfaces. */
export const ALLOWED_SURFACE_ICONS = [
  "activity",
  "bar-chart-3",
  "bell",
  "bike",
  "book-open",
  "bookmark",
  "bot",
  "brain",
  "calendar",
  "calendar-days",
  "camera",
  "car",
  "checklist",
  "clipboard",
  "cloud",
  "coffee",
  "compass",
  "database",
  "droplet",
  "file-text",
  "flag",
  "flame",
  "folder",
  "gamepad-2",
  "gem",
  "globe",
  "hash",
  "headphones",
  "heart",
  "home",
  "image",
  "layout-grid",
  "line-chart",
  "list",
  "map-pin",
  "message-circle",
  "mic",
  "moon",
  "music",
  "orbit",
  "paintbrush",
  "palette",
  "pen-line",
  "pie-chart",
  "plane",
  "radio",
  "rss",
  "settings",
  "sparkles",
  "star",
  "sun",
  "tag",
  "target",
  "train-front",
  "trophy",
  "user",
  "users",
  "video",
  "wand-sparkles",
  "zap",
] as const;

export type AllowedSurfaceIcon = (typeof ALLOWED_SURFACE_ICONS)[number];

export function isAllowedSurfaceIcon(value: string): value is AllowedSurfaceIcon {
  return (ALLOWED_SURFACE_ICONS as readonly string[]).includes(value.trim());
}

export const SURFACE_ICON_GROUPS: Record<string, readonly AllowedSurfaceIcon[]> = {
  builtin: [
    "home",
    "message-circle",
    "layout-grid",
    "book-open",
    "calendar",
    "calendar-days",
    "globe",
    "orbit",
    "zap",
    "calendar",
    "radio",
    "activity",
    "settings",
  ],
  creative: [
    "pen-line",
    "sparkles",
    "paintbrush",
    "palette",
    "wand-sparkles",
    "music",
    "image",
    "camera",
    "video",
    "mic",
    "headphones",
  ],
  life: ["brain", "heart", "coffee", "star", "gem", "trophy", "gamepad-2", "bookmark", "flag", "target"],
  data: [
    "bar-chart-3",
    "line-chart",
    "pie-chart",
    "database",
    "rss",
    "bell",
    "hash",
    "tag",
    "list",
    "checklist",
    "clipboard",
    "file-text",
    "folder",
  ],
  travel: ["train-front", "plane", "car", "bike", "map-pin", "compass"],
  weather: ["sun", "moon", "cloud", "flame", "droplet"],
  people: ["user", "users", "bot"],
};
