import {
  Activity,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  CheckSquare,
  Clipboard,
  Cloud,
  Coffee,
  Compass,
  Database,
  Droplet,
  FileText,
  Flag,
  Flame,
  Folder,
  Gamepad2,
  Gem,
  Globe,
  Hash,
  Headphones,
  Heart,
  Home,
  Image,
  LayoutGrid,
  LineChart,
  List,
  MapPin,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Orbit,
  Paintbrush,
  Palette,
  PanelsTopLeft,
  PenLine,
  PieChart,
  Plane,
  Radio,
  Rss,
  Settings,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  TrainFront,
  Trophy,
  User,
  Users,
  Video,
  WandSparkles,
  Zap,
  type Icon,
} from "@lucide/svelte";
import { isAllowedSurfaceIcon } from "$lib/utils/environmentIconCatalog";

const ICONS: Record<string, typeof Icon> = {
  activity: Activity,
  "bar-chart-3": BarChart3,
  bell: Bell,
  bike: Bike,
  "book-open": BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  brain: Brain,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  camera: Camera,
  car: Car,
  checklist: CheckSquare,
  clipboard: Clipboard,
  cloud: Cloud,
  coffee: Coffee,
  compass: Compass,
  database: Database,
  droplet: Droplet,
  "file-text": FileText,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  "gamepad-2": Gamepad2,
  gem: Gem,
  globe: Globe,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  image: Image,
  "layout-grid": LayoutGrid,
  "line-chart": LineChart,
  list: List,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  mic: Mic,
  moon: Moon,
  music: Music,
  orbit: Orbit,
  paintbrush: Paintbrush,
  palette: Palette,
  "panels-top-left": PanelsTopLeft,
  "pen-line": PenLine,
  "pie-chart": PieChart,
  plane: Plane,
  radio: Radio,
  rss: Rss,
  settings: Settings,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  "train-front": TrainFront,
  trophy: Trophy,
  user: User,
  users: Users,
  video: Video,
  "wand-sparkles": WandSparkles,
  zap: Zap,
};

export function environmentIcon(name: string): typeof Icon {
  const key = name.trim();
  if (isAllowedSurfaceIcon(key)) {
    return ICONS[key] ?? Sparkles;
  }
  return ICONS[key] ?? Sparkles;
}
