use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let config_path = Path::new(&manifest_dir).join("../public/installer-config.json");

    let (mut base_url, mut channel) = if config_path.exists() {
        let content = fs::read_to_string(&config_path).unwrap_or_default();
        parse_installer_config(&content)
    } else {
        (String::new(), "stable".to_string())
    };

    if let Ok(env_base) = env::var("MEDOUSA_RELEASE_BASE_URL") {
        if !env_base.trim().is_empty() {
            base_url = env_base;
        }
    }
    if let Ok(env_channel) = env::var("MEDOUSA_RELEASE_CHANNEL") {
        if !env_channel.trim().is_empty() {
            channel = env_channel;
        }
    }

    let out_path = Path::new(&manifest_dir).join("src/embedded_release.rs");
    let base_literal = if base_url.trim().is_empty() {
        "None".to_string()
    } else {
        let escaped = base_url.trim_end_matches('/').replace('\\', "\\\\").replace('"', "\\\"");
        format!("Some(\"{escaped}\")")
    };
    let channel_escaped = channel.replace('\\', "\\\\").replace('"', "\\\"");

    fs::write(
        &out_path,
        format!(
            "// @generated by build.rs — do not edit\n\
             pub const RELEASE_BASE_URL: Option<&'static str> = {base_literal};\n\
             pub const RELEASE_CHANNEL: &str = \"{channel_escaped}\";\n"
        ),
    )
    .expect("write embedded_release.rs");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-env-changed=MEDOUSA_RELEASE_BASE_URL");
    println!("cargo:rerun-if-env-changed=MEDOUSA_RELEASE_CHANNEL");

    tauri_build::build();
}

fn parse_installer_config(content: &str) -> (String, String) {
    let value: serde_json::Value = serde_json::from_str(content).unwrap_or(serde_json::Value::Null);
    let base = value
        .get("releaseBaseUrl")
        .and_then(|entry| entry.as_str())
        .unwrap_or("")
        .trim()
        .to_string();
    let channel = value
        .get("releaseChannel")
        .and_then(|entry| entry.as_str())
        .unwrap_or("stable")
        .trim()
        .to_string();
    (base, channel)
}
