# DO NOT EDIT — generated by scripts/gen-python-types.py
# Source: sdk-contract/medousa-types.schema.json (cargo run -p medousa-types-schema)

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class MedousaModel(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)


# generated by datamodel-codegen:
#   filename:  tmp1kq8n5of.json

class ArchiveAskJobRequest(MedousaModel):
    purge_output: bool | None = False


class ArchiveAskJobResponse(MedousaModel):
    archived: bool
    job_id: str
    message: str


class ArtifactCommandResponse(MedousaModel):
    rendered_output: str
    selected_context_pack_query: str | None = None


class ArtifactFetchRequest(MedousaModel):
    artifact_id: str
    session_id: str


class ArtifactFetchResponse(MedousaModel):
    artifact_id: str
    body: str
    byte_size: int = Field(..., ge=0)
    height_px: int | None = Field(None, ge=0)
    label: str
    mime: str
    presentation: str | None = None


class ArtifactListUiRequest(MedousaModel):
    limit: int | None = Field(50, ge=0)
    query: str | None = None
    session_id: str | None = None


class AskJobCompleteActionsRequest(MedousaModel):
    notify_channel: str | None = None
    write_journal_path: str | None = None


class AskJobCompleteActionsResponse(MedousaModel):
    job_id: str
    journal_path: str | None = None
    message: str
    notified_channel: str | None = None
    ok: bool


class DeleteRecurringResponse(MedousaModel):
    deleted: bool
    recurring_id: str


class EnqueueAskRequest(MedousaModel):
    additional_manuscript_ids: list[str] | None = Field(
        None, description='Extra manuscript specialties beyond `manuscript_id`.'
    )
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    manuscript_id: str | None = Field(
        None, description='Primary YAML manuscript specialty for the ask turn.'
    )
    max_turns: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    suggested_capability_ids: list[str] | None = Field(
        None, description='Capability catalog ids the operator suggests for this ask.'
    )


class EnqueuePromptRequest(MedousaModel):
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    system_prompt: str | None = None


class EnqueueReportRequest(MedousaModel):
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    max_turns: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    query: str


class EnqueueResponse(MedousaModel):
    accepted_at_utc: AwareDatetime
    job_id: str
    queue: str


class HealthResponse(MedousaModel):
    active_profile_display_name: str | None = Field(
        None, description='Human label for `active_profile_id`.'
    )
    active_profile_id: str | None = Field(
        None, description='Active workshop identity profile (`user:{slug}`).'
    )
    agent_runtime_version: str | None = 'centralized-v1'
    backend: str
    last_agent_turn_at_utc: AwareDatetime | None = None
    last_agent_turn_latency_ms: int | None = Field(None, ge=0)
    now_utc: AwareDatetime
    status: str
    tool_registry_count: int | None = Field(0, ge=0)
    worker_id: str


class IngestResponse(MedousaModel):
    is_new_session: bool = Field(
        ...,
        description='Whether this is a brand-new session (first message or after /new)',
    )
    job_id: str | None = Field(
        None, description='If a job was enqueued, its id (for polling/streaming)'
    )
    reply: str = Field(
        ..., description='Immediate text reply (help text, confirmation, error message)'
    )
    session_id: str = Field(
        ..., description='The resolved or created session_id for this channel+user pair'
    )
    stream_id: str | None = Field(
        None, description='SSE stream id when a job-backed ask is processing'
    )
    stream_ready: bool | None = Field(
        False, description='Whether the stream endpoint is ready for subscription'
    )
    stream_url: str | None = Field(
        None, description='Absolute URL for SSE stream consumption by adapters'
    )


class InteractiveTurnResponse(MedousaModel):
    accepted_at_utc: AwareDatetime
    daemon_notice: str | None = None
    fallback_reason: str | None = None
    fallback_to_local: bool
    stream_ready: bool
    stream_url: str
    turn_id: str


class JobResultResponse(MedousaModel):
    attempt_count: int = Field(..., ge=0)
    interim_text: str | None = None
    is_terminal: bool
    job_id: str
    latest_execution_id: str | None = None
    latest_outcome: str | None = None
    output_text: str | None = None
    status: str


class LocalEngineStatus(MedousaModel):
    baseUrl: str
    bind: str | None = None
    featureEnabled: bool
    inferenceBackend: str | None = None
    loaded: bool
    message: str
    modelAlias: str | None = None
    modelRepo: str | None = None


class LocalModelDownloadRequest(MedousaModel):
    modelId: str


class ModelDownloadProgress1(MedousaModel):
    bytesDone: int = Field(..., ge=0)
    bytesTotal: int = Field(..., ge=0)
    currentFile: str | None = None
    error: str | None = None
    jobId: str
    message: str
    modelId: str
    percent: float
    phase: str


class RecurringDeliveryResponse(MedousaModel):
    delivery: Any | None = None
    delivery_label: str
    recurring_id: str


class RegisterRecurringPromptRequest(MedousaModel):
    cron_expr: str
    delivery: Any | None = Field(
        None,
        description='Optional channel push target for each successful materialized run.',
    )
    display_name: str | None = Field(
        None, description='Human-readable title for Automations list rows.'
    )
    enabled: bool | None = None
    execution_mode: str | None = Field(
        None, description='`agent_turn` (default) or `prompt` (single LLM, no tools).'
    )
    id: str | None = None
    jitter_seconds: int | None = None
    manuscript_id: str | None = Field(
        None,
        description='Optional YAML identity manuscript (loads task template, tool allowlist, pins).',
    )
    max_attempts: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    queue: str | None = None
    session_id: str | None = Field(
        None,
        description='Medousa session id for `delivery.mode=linked_channel` (defaults to `recurring-{id}`).',
    )
    system_prompt: str | None = None
    timezone: str | None = None


class RegisterRecurringResponse(MedousaModel):
    cron_expr: str
    next_run_at_utc: AwareDatetime
    queue: str
    recurring_id: str
    timezone: str


class SessionAppendTurnResponse(MedousaModel):
    session_id: str
    stored: bool


class SessionDeleteResponse(MedousaModel):
    cancelled_active_turn: bool
    deleted: bool
    locus_nodes_deleted: int = Field(..., ge=0)
    locus_purged: bool
    session_id: str


class SessionSetDisplayNameRequest(MedousaModel):
    display_name: str


class SessionSetDisplayNameResponse(MedousaModel):
    display_name: str
    session_id: str


class TurnBudgetApproveRequest(MedousaModel):
    extra_rounds: int | None = Field(None, ge=0)
    resolved_by: str | None = None


class TurnBudgetDenyRequest(MedousaModel):
    resolved_by: str | None = None


class UpdateRecurringRequest(MedousaModel):
    cron_expr: str | None = None
    delivery: Any | None = Field(
        None,
        description='Replace delivery binding; pass `{ "delivery": null }` to clear channel push.',
    )
    display_name: str | None = None
    enabled: bool | None = None
    timezone: str | None = None


class UpdateRecurringResponse(MedousaModel):
    cron_expr: str
    enabled: bool
    next_run_at_utc: AwareDatetime
    recurring_id: str
    timezone: str


class VaultAddRootRequest(MedousaModel):
    id: str | None = None
    label: str
    path: str


class VaultBacklinksResponse(MedousaModel):
    backlinks: list[str]
    path: str


class VaultDeleteResponse(MedousaModel):
    deleted: bool
    path: str


class VaultSetActiveRootRequest(MedousaModel):
    rootId: str


class VaultTagsListResponse(MedousaModel):
    count: int = Field(..., ge=0)
    tags: list[str]


class VaultWriteRequest(MedousaModel):
    auto_workshop_tags: bool | None = Field(
        True, description='Merge default workshop + vault tags on write (default true).'
    )
    content: str
    path: str | None = None
    semantic_tags: list[str] | None = None
    session_id: str | None = Field(
        None,
        description='Chat session id for workshop linking tags (`chat:…`, `session`, `profile:…`).',
    )


class WorkspaceLinkVaultRequest(MedousaModel):
    vault_path: str


class ArtifactCommandSpec(RootModel[Any]):
    root: Any


class ArtifactSummary(RootModel[Any]):
    root: Any


class ArtifactVerificationPolicyInput(RootModel[Any]):
    root: Any


class CapabilityImplementations(RootModel[Any]):
    root: Any


class CapabilityListEntry(RootModel[Any]):
    root: Any


class CapabilityRecommendation(RootModel[Any]):
    root: Any


class CatalogModelEntry(RootModel[Any]):
    root: Any


class ConversationTurn(RootModel[Any]):
    root: Any


class HardwareProfile(RootModel[Any]):
    root: Any


class HardwareTier(RootModel[Any]):
    root: Any


class IngestAttachment(RootModel[Any]):
    root: Any


class InstalledModelRecord(RootModel[Any]):
    root: Any


class JobCitationResponse(RootModel[Any]):
    root: Any


class JobEvidenceReportResponse(RootModel[Any]):
    root: Any


class McpGatewayHealthSnapshot(RootModel[Any]):
    root: Any


class McpGatewayServerRuntime(RootModel[Any]):
    root: Any


class MediaRef(RootModel[Any]):
    root: Any


class ModelDownloadProgress(RootModel[Any]):
    root: Any


class RecurringDefinitionEntry(RootModel[Any]):
    root: Any


class RecurringRunEntry(RootModel[Any]):
    root: Any


class RuntimeConfigCommandSpec(RootModel[Any]):
    root: Any


class RuntimeVerifyPolicyState(RootModel[Any]):
    root: Any


class SessionHistorySummary(RootModel[Any]):
    root: Any


class StageRouteCommandSpec(RootModel[Any]):
    root: Any


class StageRoutingMatrix(RootModel[Any]):
    root: Any


class StreamToolArtifactRef(RootModel[Any]):
    root: Any


class StreamUiArtifact(RootModel[Any]):
    root: Any


class TurnBudgetRequestRecord(RootModel[Any]):
    root: Any


class TurnSurfaceContext(RootModel[Any]):
    root: Any


class VaultNote(RootModel[Any]):
    root: Any


class VaultRootView(RootModel[Any]):
    root: Any


class VaultSearchHit(RootModel[Any]):
    root: Any


class WorkCard(RootModel[Any]):
    root: Any


class WorkCardAssociations(RootModel[Any]):
    root: Any


class WorkspaceEvent(RootModel[Any]):
    root: Any


class WorkspaceSnapshot(RootModel[Any]):
    root: Any


class ArtifactCommandRequest(MedousaModel):
    command: ArtifactCommandSpec
    selected_context_pack_query: str | None = None
    session_id: str
    verification_policy: ArtifactVerificationPolicyInput | None = None
    verifier_route_label: str | None = None


class ArtifactListUiResponse(MedousaModel):
    artifacts: list[ArtifactSummary]


class CapabilityListResponse(MedousaModel):
    capabilities: list[CapabilityListEntry]


class CapabilityResolveResponse(MedousaModel):
    capability: str
    description: str | None = None
    gateway_unreachable: bool | None = None
    implementations: CapabilityImplementations
    recommended: CapabilityRecommendation | None = None
    title: str


class IngestRequest(MedousaModel):
    attachments: list[IngestAttachment] | None = Field(
        [],
        description='Optional attachment payloads merged into ask prompts',
        validate_default=True,
    )
    channel: str = Field(
        ..., description='Channel type identifier, e.g. "telegram", "discord", "cli"'
    )
    channel_id: str = Field(
        ...,
        description='Channel/chat/conversation identifier, e.g. "telegram:chat:67890"',
    )
    text: str = Field(
        ..., description='The text content of the message (command or prompt)'
    )
    user_id: str = Field(
        ...,
        description='User identifier within the channel, e.g. "telegram:user:12345"',
    )


class InteractiveTurnRequest(MedousaModel):
    additional_manuscript_ids: list[str] | None = None
    identity_user_id: str | None = Field(
        None,
        description='Optional identity principal override (debug/internal). Default: active workshop profile.',
    )
    manuscript_id: str | None = Field(
        None,
        description='YAML manuscript specialty for ranked digest + scheduled tool allowlist.',
    )
    max_tool_rounds: int | None = Field(
        None,
        description='When set, overrides `tui_defaults.json` for this turn (TUI live settings).',
        ge=0,
    )
    media_refs: list[MediaRef] | None = Field(
        [],
        description='User media uploaded to local medousa/media/ before this turn (P5a).',
        validate_default=True,
    )
    model: str
    persist_user_turn: bool
    prompt: str
    provider: str
    reasoning_effort: str | None = ''
    response_depth_mode: str
    retry_runtime_max_rounds: int | None = Field(None, ge=0)
    scheduled_tool_allowlist: list[str] | None = None
    session_id: str
    stage_routing: StageRoutingMatrix
    suggested_capability_ids: list[str] | None = None
    surface: TurnSurfaceContext | None = Field(
        None,
        description='Channel adapter context for ambient prompting (ingest/TUI surfaces).',
    )
    voice_appendix: str | None = None
    voice_preset_id: str | None = Field(
        None,
        description='Composer voice stance — short appendix block (not a manuscript specialty).',
    )


class InteractiveTurnStreamEvent(MedousaModel):
    budget_request_id: str | None = Field(
        None,
        description='Turn budget approval pause — card id for Home deep link / notifications.',
    )
    browser_challenge_url: str | None = Field(
        None,
        description='URL the client should load in Agent Browser WebView during CAPTCHA handoff.',
    )
    browser_session_id: str | None = Field(
        None,
        description='Agent Browser session id for CAPTCHA / client-executed search handoff.',
    )
    content_delta: str | None = None
    debug_message: str | None = Field(
        None,
        description='Engine/TUI telemetry — shown only when the operator opts into engine details.',
    )
    emitted_at_utc: AwareDatetime
    event_type: str
    final_text: str | None = None
    message: str
    operator_message: str | None = Field(
        None,
        description='Human-facing status whisper for rich surfaces (Home default).',
    )
    phase: str
    previous_artifact_id: str | None = Field(
        None,
        description='Previous artifact id when cognition_artifact_write supersedes a revision.',
    )
    reasoning_delta: str | None = None
    requested_rounds: int | None = Field(None, ge=0)
    root_artifact_id: str | None = Field(
        None, description='Root artifact lineage id for revision chains.'
    )
    seq: int = Field(
        0,
        description='Monotonic per-turn sequence for SSE reconnect replay (`?since=`).',
    )
    terminal: bool
    tool_artifact_refs: list[StreamToolArtifactRef] | None = None
    tool_input_summary: str | None = None
    tool_name: str | None = None
    tool_names: list[str] | None = None
    tool_output_summary: str | None = None
    tool_round: int | None = Field(None, ge=0)
    tool_run_id: str | None = Field(
        None, description='Structured tool bus (P1) — correlates started/finished pair.'
    )
    tool_status: str | None = None
    turn_id: str
    ui_artifact: StreamUiArtifact | None = Field(
        None,
        description='Rich UI artifact presented inline in chat (cognition_ui_present).',
    )
    work_id: str | None = Field(
        None, description='Turn worker handoff — workspace card id (`work-…`).'
    )


class JobReportResponse(MedousaModel):
    attempt_count: int = Field(..., ge=0)
    citations: list[JobCitationResponse]
    evidence_report: JobEvidenceReportResponse | None = None
    is_terminal: bool
    job_id: str
    latest_execution_id: str | None = None
    latest_outcome: str | None = None
    output_text: str | None = None
    status: str


class LocalCatalogResponse(MedousaModel):
    familyDefault: str
    models: list[CatalogModelEntry]
    recommendedModelId: str
    tier: HardwareTier
    tierLabel: str


class LocalHardwareResponse(MedousaModel):
    compiledBackends: list[str]
    engineAvailable: bool
    message: str
    profile: HardwareProfile


class LocalModelDownloadResponse(MedousaModel):
    job: ModelDownloadProgress


class LocalModelsResponse(MedousaModel):
    activeDownloads: list[ModelDownloadProgress]
    installed: list[InstalledModelRecord]


class McpGatewayStatusResponse(MedousaModel):
    gatewayUrl: str
    health: McpGatewayHealthSnapshot | None = None
    message: str
    reachable: bool
    servers: list[McpGatewayServerRuntime]


class RecurringListResponse(MedousaModel):
    count: int = Field(..., ge=0)
    recurring: list[RecurringDefinitionEntry]


class RecurringRunsResponse(MedousaModel):
    count: int = Field(..., ge=0)
    recurring_id: str
    runs: list[RecurringRunEntry]


class RuntimeConfigCommandRequest(MedousaModel):
    command: RuntimeConfigCommandSpec
    current_model: str
    current_provider: str
    current_reasoning_effort: str | None = ''
    current_response_depth_mode: str
    draft_model: str
    draft_provider: str


class RuntimeConfigCommandResponse(MedousaModel):
    next_draft_model: str
    next_draft_provider: str
    next_reasoning_effort: str
    next_response_depth_mode: str
    next_verify_policy_draft: RuntimeVerifyPolicyState | None = None
    rendered_output: str | None = None
    should_apply_settings: bool
    should_persist_depth_defaults: bool
    should_persist_reasoning_defaults: bool


class SessionAppendTurnRequest(MedousaModel):
    turn: ConversationTurn


class SessionHistoryListResponse(MedousaModel):
    next_cursor: str | None = None
    sessions: list[SessionHistorySummary]


class SessionHistoryResponse(MedousaModel):
    session_id: str
    turns: list[ConversationTurn]


class StageRouteCommandRequest(MedousaModel):
    command: StageRouteCommandSpec
    model: str
    provider: str
    stage_routing: StageRoutingMatrix


class StageRouteCommandResponse(MedousaModel):
    rendered_output: str
    stage_routing: StageRoutingMatrix


class TurnBudgetRequestListResponse(MedousaModel):
    requests: list[TurnBudgetRequestRecord]


class TurnBudgetRequestResponse(MedousaModel):
    message: str
    request: TurnBudgetRequestRecord


class VaultNoteContentResponse(MedousaModel):
    content: str
    note: VaultNote


class VaultNotesListResponse(MedousaModel):
    notes: list[VaultNote]


class VaultRootsResponse(MedousaModel):
    activeRootId: str
    roots: list[VaultRootView]


class VaultSearchResponse(MedousaModel):
    hits: list[VaultSearchHit]
    query: str


class VaultWriteResponse(MedousaModel):
    created: bool
    note: VaultNote


class WorkspaceCardActionResponse(MedousaModel):
    action: str
    associations: WorkCardAssociations | None = None
    card_id: str
    job_id: str | None = None
    job_succeeded: bool | None = None
    message: str
    ok: bool
    replayed: bool | None = None
    workspace_revision: int = Field(..., ge=0)


class WorkspaceStreamEvent(MedousaModel):
    card: WorkCard | None = None
    counts: dict[str, Any] | None = None
    emitted_at_utc: AwareDatetime
    feed_event: WorkspaceEvent | None = None
    snapshot: WorkspaceSnapshot | None = None
    stream_event_type: str
    workspace_revision: int = Field(..., ge=0)