# DO NOT EDIT — generated by scripts/gen-python-types.py
# Source: sdk-contract/medousa-types.schema.json (cargo run -p medousa-types-schema)

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class MedousaModel(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class AgentPermissionResolveRequest(MedousaModel):
    resolved_by: str | None = None


class AgentRuntimeInfo(MedousaModel):
    available: bool
    command: str | None = None
    detail: str | None = None
    runtime: str
    uses_native_turns: bool | None = Field(
        False,
        description='Native Medousa turns use `/v1/turns` — not `/v1/agents/sessions`.',
    )


class AgentSessionPromptRequest(MedousaModel):
    prompt: str


class AgentSessionPromptResponse(MedousaModel):
    accepted: bool
    agent_session_id: str


class ArchiveAskJobRequest(MedousaModel):
    purge_output: bool | None = False


class ArchiveAskJobResponse(MedousaModel):
    archived: bool
    job_id: str
    message: str


class ArtifactCommandResponse(MedousaModel):
    rendered_output: str
    selected_context_pack_query: str | None = None


class ArtifactDeleteRequest(MedousaModel):
    artifact_id: str
    session_id: str


class ArtifactDeleteResponse(MedousaModel):
    deleted_artifact_ids: list[str]


class ArtifactFetchRequest(MedousaModel):
    artifact_id: str
    session_id: str


class ArtifactFetchResponse(MedousaModel):
    artifact_id: str
    body: str
    byte_size: int = Field(..., ge=0)
    height_px: int | None = Field(None, ge=0)
    label: str
    mime: str
    payload_path: str | None = None
    presentation: str | None = None


class ArtifactListUiRequest(MedousaModel):
    limit: int | None = Field(50, ge=0)
    query: str | None = None
    session_id: str | None = None


class ArtifactWriteRequest(MedousaModel):
    artifact_id: str
    height_px: int | None = Field(None, ge=0)
    html: str
    if_match_hash64: str | None = None
    presentation: str | None = None
    session_id: str
    title: str


class ArtifactWriteResponse(MedousaModel):
    artifact_id: str
    hash64: str
    label: str
    supersedes_artifact_id: str


class AskJobCompleteActionsRequest(MedousaModel):
    notify_channel: str | None = None
    write_journal_path: str | None = None


class AskJobCompleteActionsResponse(MedousaModel):
    job_id: str
    journal_path: str | None = None
    message: str
    notified_channel: str | None = None
    ok: bool


class CalendarDeleteResponse(MedousaModel):
    calendar_path: str
    deleted: bool
    uid: str


class CalendarExportResponse(MedousaModel):
    calendar_path: str
    content_type: str
    ics: str


class CalendarImportRequest(MedousaModel):
    calendar_path: str | None = None
    ics: str = Field(..., description='Raw RFC 5545 text.')


class CalendarImportResponse(MedousaModel):
    calendar_path: str
    imported: int = Field(..., ge=0)
    skipped: int | None = Field(
        0,
        description='Non-event components (and other non-fatal skips) that were not imported.',
        ge=0,
    )
    updated: int = Field(..., ge=0)
    warnings: list[str] | None = Field(
        [], description='Human-readable skip / fallback notes for the import run.'
    )


class CancelAgentSessionResponse(MedousaModel):
    agent_session_id: str
    cancelled: bool
    message: str


class ComponentRuntimeEventsQuery(MedousaModel):
    limit: int | None = Field(None, ge=0)
    profileId: str | None = None


class ComponentRuntimeEventsResponse(MedousaModel):
    accepted: int = Field(..., ge=0)
    ok: bool


class ComponentRuntimeProbeResult(MedousaModel):
    componentId: str
    errors: list[str] | None = []
    probeId: str
    profileId: str | None = None
    storeReady: bool
    storeRoundTripOk: bool


class ComponentStoreDeleteResponse(MedousaModel):
    componentId: str
    deleted: bool
    key: str
    ok: bool


class ComponentStoreGetResponse(MedousaModel):
    componentId: str
    entries: dict[str, Any] | None = None


class ComponentStoreListResponse(MedousaModel):
    componentId: str
    keys: list[str]


class ComponentStoreQuery(MedousaModel):
    key: str | None = None
    profileId: str | None = None


class ComponentStoreSetRequest(MedousaModel):
    profileId: str | None = None
    value: Any


class ComponentStoreSetResponse(MedousaModel):
    componentId: str
    key: str
    ok: bool
    updatedAtUtc: AwareDatetime


class CreateAgentSessionResponse(MedousaModel):
    accepted_at_utc: AwareDatetime
    agent_session_id: str
    phase: str
    runtime: str
    session_id: str
    stream_ready: bool
    stream_url: str


class DeleteRecurringResponse(MedousaModel):
    deleted: bool
    recurring_id: str


class EnqueueAskRequest(MedousaModel):
    additional_manuscript_ids: list[str] | None = Field(
        None, description='Extra manuscript specialties beyond `manuscript_id`.'
    )
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    manuscript_id: str | None = Field(
        None, description='Primary YAML manuscript specialty for the ask turn.'
    )
    max_turns: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    suggested_capability_ids: list[str] | None = Field(
        None, description='Capability catalog ids the operator suggests for this ask.'
    )


class EnqueuePromptRequest(MedousaModel):
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    system_prompt: str | None = None


class EnqueueReportRequest(MedousaModel):
    identity_channel_id: str | None = None
    identity_persona_id: str | None = None
    identity_user_id: str | None = None
    max_turns: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    query: str


class EnqueueResponse(MedousaModel):
    accepted_at_utc: AwareDatetime
    job_id: str
    queue: str


class EnvironmentStreamQuery(MedousaModel):
    profileId: str | None = None
    sinceRevision: int | None = Field(None, ge=0)


class EnvironmentValidateResponse(MedousaModel):
    errors: list[str]
    valid: bool


class FeedReadRequest(MedousaModel):
    profileId: str | None = None
    seq: int | None = Field(None, ge=0)


class FeedStreamQuery(MedousaModel):
    profileId: str | None = None


class FeedTailQuery(MedousaModel):
    limit: int | None = Field(None, ge=0)
    profileId: str | None = None


class HealthResponse(MedousaModel):
    active_profile_display_name: str | None = Field(
        None, description='Human label for `active_profile_id`.'
    )
    active_profile_id: str | None = Field(
        None, description='Active workshop identity profile (`user:{slug}`).'
    )
    agent_runtime_version: str | None = 'centralized-v1'
    backend: str
    last_agent_turn_at_utc: AwareDatetime | None = None
    last_agent_turn_latency_ms: int | None = Field(None, ge=0)
    now_utc: AwareDatetime
    status: str
    tool_registry_count: int | None = Field(0, ge=0)
    worker_id: str


class IngestResponse(MedousaModel):
    is_new_session: bool = Field(
        ...,
        description='Whether this is a brand-new session (first message or after /new)',
    )
    job_id: str | None = Field(
        None, description='If a job was enqueued, its id (for polling/streaming)'
    )
    reply: str = Field(
        ..., description='Immediate text reply (help text, confirmation, error message)'
    )
    session_id: str = Field(
        ..., description='The resolved or created session_id for this channel+user pair'
    )
    stream_id: str | None = Field(
        None, description='SSE stream id when a job-backed ask is processing'
    )
    stream_ready: bool | None = Field(
        False, description='Whether the stream endpoint is ready for subscription'
    )
    stream_url: str | None = Field(
        None, description='Absolute URL for SSE stream consumption by adapters'
    )


class InteractiveTurnResponse(MedousaModel):
    accepted_at_utc: AwareDatetime
    daemon_notice: str | None = None
    fallback_reason: str | None = None
    fallback_to_local: bool
    stream_ready: bool
    stream_url: str
    turn_id: str


class JobResultResponse(MedousaModel):
    attempt_count: int = Field(..., ge=0)
    interim_text: str | None = None
    is_terminal: bool
    job_id: str
    latest_execution_id: str | None = None
    latest_outcome: str | None = None
    output_text: str | None = None
    status: str


class LocalEngineStatus(MedousaModel):
    baseUrl: str
    bind: str | None = None
    featureEnabled: bool
    inferenceBackend: str | None = None
    loaded: bool
    message: str
    modelAlias: str | None = None
    modelRepo: str | None = None


class LocalModelDownloadRequest(MedousaModel):
    modelId: str


class ModelDownloadProgress1(MedousaModel):
    bytesDone: int = Field(..., ge=0)
    bytesTotal: int = Field(..., ge=0)
    currentFile: str | None = None
    error: str | None = None
    jobId: str
    message: str
    modelId: str
    percent: float
    phase: str


class RecurringDeliveryResponse(MedousaModel):
    delivery: Any | None = None
    delivery_label: str
    recurring_id: str


class RegisterRecurringPromptRequest(MedousaModel):
    cron_expr: str
    delivery: Any | None = Field(
        None,
        description='Optional channel push target for each successful materialized run.',
    )
    display_name: str | None = Field(
        None, description='Human-readable title for Automations list rows.'
    )
    enabled: bool | None = None
    execution_mode: str | None = Field(
        None, description='`agent_turn` (default) or `prompt` (single LLM, no tools).'
    )
    feeds: Any | None = Field(
        None,
        description='Optional environment feed ids to publish on each materialized run terminal.',
    )
    id: str | None = None
    jitter_seconds: int | None = None
    manuscript_id: str | None = Field(
        None,
        description='Optional YAML identity manuscript (loads task template, tool allowlist, pins).',
    )
    max_attempts: int | None = Field(None, ge=0)
    model_hint: str | None = None
    policy_profile: str | None = None
    prompt: str
    queue: str | None = None
    session_id: str | None = Field(
        None,
        description='Medousa session id for `delivery.mode=linked_channel` (defaults to `recurring-{id}`).',
    )
    system_prompt: str | None = None
    timezone: str | None = None


class RegisterRecurringResponse(MedousaModel):
    cron_expr: str
    next_run_at_utc: AwareDatetime
    queue: str
    recurring_id: str
    timezone: str


class SessionAppendTurnResponse(MedousaModel):
    session_id: str
    stored: bool


class SessionDeleteResponse(MedousaModel):
    cancelled_active_turn: bool
    deleted: bool
    locus_nodes_deleted: int = Field(..., ge=0)
    locus_purged: bool
    session_id: str


class SessionSetDisplayNameRequest(MedousaModel):
    display_name: str


class SessionSetDisplayNameResponse(MedousaModel):
    display_name: str
    session_id: str


class TurnBudgetApproveRequest(MedousaModel):
    extra_rounds: int | None = Field(None, ge=0)
    resolved_by: str | None = None


class TurnBudgetDenyRequest(MedousaModel):
    resolved_by: str | None = None


class UpdateRecurringRequest(MedousaModel):
    cron_expr: str | None = None
    delivery: Any | None = Field(
        None,
        description='Replace delivery binding; pass `{ "delivery": null }` to clear channel push.',
    )
    display_name: str | None = None
    enabled: bool | None = None
    feeds: Any | None = Field(
        None,
        description='Replace feed binding; pass `{ "feeds": null }` to clear feed publish.',
    )
    timezone: str | None = None


class UpdateRecurringResponse(MedousaModel):
    cron_expr: str
    enabled: bool
    next_run_at_utc: AwareDatetime
    recurring_id: str
    timezone: str


class VaultAddRootRequest(MedousaModel):
    id: str | None = None
    label: str
    path: str


class VaultBacklinksResponse(MedousaModel):
    backlinks: list[str]
    path: str


class VaultDeleteResponse(MedousaModel):
    deleted: bool
    path: str


class VaultSetActiveRootRequest(MedousaModel):
    rootId: str


class VaultTagsListResponse(MedousaModel):
    count: int = Field(..., ge=0)
    tags: list[str]


class VaultWriteRequest(MedousaModel):
    auto_workshop_tags: bool | None = Field(
        True, description='Merge default workshop + vault tags on write (default true).'
    )
    content: str
    path: str | None = None
    semantic_tags: list[str] | None = None
    session_id: str | None = Field(
        None,
        description='Chat session id for workshop linking tags (`chat:…`, `session`, `profile:…`).',
    )


class WorkspaceLinkVaultRequest(MedousaModel):
    vault_path: str


class AgentPermissionRequestRecord(RootModel[Any]):
    root: Any


class AgentPermissionRequestStatus(RootModel[Any]):
    root: Any


class AgentRuntimeInfoModel(RootModel[Any]):
    root: Any


class ArtifactCommandSpec(RootModel[Any]):
    root: Any


class ArtifactSummary(RootModel[Any]):
    root: Any


class ArtifactVerificationPolicyInput(RootModel[Any]):
    root: Any


class CalendarAlarm(RootModel[Any]):
    root: Any


class CalendarEvent(RootModel[Any]):
    root: Any


class CapabilityImplementations(RootModel[Any]):
    root: Any


class CapabilityListEntry(RootModel[Any]):
    root: Any


class CapabilityRecommendation(RootModel[Any]):
    root: Any


class CatalogModelEntry(RootModel[Any]):
    root: Any


class ComponentDef(RootModel[Any]):
    root: Any


class ComponentFeedPatch(RootModel[Any]):
    root: Any


class ComponentRuntimeEvent(RootModel[Any]):
    root: Any


class ComponentRuntimeEventInput(RootModel[Any]):
    root: Any


class ComponentRuntimeProbeRequest(RootModel[Any]):
    root: Any


class ContextUsageReport(RootModel[Any]):
    root: Any


class ConversationTurn(RootModel[Any]):
    root: Any


class CustomViewSurfaceStatus(RootModel[Any]):
    root: Any


class EnvironmentPendingProposal(RootModel[Any]):
    root: Any


class EnvironmentSpec(RootModel[Any]):
    root: Any


class EnvironmentTheme(RootModel[Any]):
    root: Any


class FeedEvent(RootModel[Any]):
    root: Any


class FeedListEntry(RootModel[Any]):
    root: Any


class HardwareProfile(RootModel[Any]):
    root: Any


class HardwareTier(RootModel[Any]):
    root: Any


class IngestAttachment(RootModel[Any]):
    root: Any


class InstalledModelRecord(RootModel[Any]):
    root: Any


class JobCitationResponse(RootModel[Any]):
    root: Any


class JobEvidenceReportResponse(RootModel[Any]):
    root: Any


class LayoutPreset(RootModel[Any]):
    root: Any


class McpGatewayHealthSnapshot(RootModel[Any]):
    root: Any


class McpGatewayServerRuntime(RootModel[Any]):
    root: Any


class MediaRef(RootModel[Any]):
    root: Any


class ModelDownloadProgress(RootModel[Any]):
    root: Any


class RecurringDefinitionEntry(RootModel[Any]):
    root: Any


class RecurringRunEntry(RootModel[Any]):
    root: Any


class RuntimeConfigCommandSpec(RootModel[Any]):
    root: Any


class RuntimeVerifyPolicyState(RootModel[Any]):
    root: Any


class SessionHistorySummary(RootModel[Any]):
    root: Any


class ShellChromeDef(RootModel[Any]):
    root: Any


class StageRouteCommandSpec(RootModel[Any]):
    root: Any


class StageRoutingMatrix(RootModel[Any]):
    root: Any


class StreamToolArtifactRef(RootModel[Any]):
    root: Any


class StreamUiArtifact(RootModel[Any]):
    root: Any


class StreamUiScene(RootModel[Any]):
    root: Any


class SurfaceDef(RootModel[Any]):
    root: Any


class TurnBudgetRequestRecord(RootModel[Any]):
    root: Any


class TurnSurfaceContext(RootModel[Any]):
    root: Any


class VaultNote(RootModel[Any]):
    root: Any


class VaultRootView(RootModel[Any]):
    root: Any


class VaultSearchHit(RootModel[Any]):
    root: Any


class WorkCard(RootModel[Any]):
    root: Any


class WorkCardAssociations(RootModel[Any]):
    root: Any


class WorkspaceEvent(RootModel[Any]):
    root: Any


class WorkspaceSnapshot(RootModel[Any]):
    root: Any


class AgentPermissionRequestListResponse(MedousaModel):
    requests: list[AgentPermissionRequestRecord]


class AgentPermissionRequestRecord1(MedousaModel):
    agent_session_id: str
    created_at_utc: AwareDatetime
    request_id: str
    resolved_at_utc: AwareDatetime | None = None
    resolved_by: str | None = None
    runtime: str
    session_id: str
    status: AgentPermissionRequestStatus
    summary: str
    updated_at_utc: AwareDatetime


class AgentPermissionResolveResponse(MedousaModel):
    request: AgentPermissionRequestRecord


class AgentRuntimeListResponse(MedousaModel):
    runtimes: list[AgentRuntimeInfoModel]


class ArtifactCommandRequest(MedousaModel):
    command: ArtifactCommandSpec
    selected_context_pack_query: str | None = None
    session_id: str
    verification_policy: ArtifactVerificationPolicyInput | None = None
    verifier_route_label: str | None = None


class ArtifactListUiResponse(MedousaModel):
    artifacts: list[ArtifactSummary]


class CalendarEventModel(MedousaModel):
    alarms: list[CalendarAlarm] | None = Field(
        None, description='VALARM display triggers before start.'
    )
    all_day: bool | None = False
    calendar_path: str
    description: str | None = None
    dtend: AwareDatetime | None = None
    dtstart: AwareDatetime
    location: str | None = None
    note_path: str | None = Field(
        None,
        description='Optional vault-relative markdown note linked to this event (`X-MEDOUSA-NOTE`).',
    )
    recurrence_id: AwareDatetime | None = Field(
        None,
        description='For expanded recurrence instances: original master UID (same as uid when not expanded).',
    )
    rrule: str | None = None
    summary: str
    uid: str


class CalendarListResponse(MedousaModel):
    calendar_path: str
    events: list[CalendarEvent]


class CalendarWriteRequest(MedousaModel):
    alarms: list[CalendarAlarm] | None = Field(
        None, description='Replace VALARM set on write (omit/empty clears).'
    )
    all_day: bool | None = False
    calendar_path: str | None = None
    description: str | None = None
    dtend: AwareDatetime | None = None
    dtstart: AwareDatetime
    location: str | None = None
    note_path: str | None = Field(
        None, description='Optional vault-relative markdown note (`X-MEDOUSA-NOTE`).'
    )
    rrule: str | None = None
    summary: str
    uid: str | None = None


class CalendarWriteResponse(MedousaModel):
    created: bool
    event: CalendarEvent


class CapabilityListResponse(MedousaModel):
    capabilities: list[CapabilityListEntry]


class CapabilityResolveResponse(MedousaModel):
    capability: str
    description: str | None = None
    gateway_unreachable: bool | None = None
    implementations: CapabilityImplementations
    recommended: CapabilityRecommendation | None = None
    title: str


class ComponentRuntimeEventsRequest(MedousaModel):
    events: list[ComponentRuntimeEventInput] | None = Field([], validate_default=True)
    profileId: str | None = None
    sessionId: str | None = None


class ComponentRuntimeEventsTailResponse(MedousaModel):
    componentId: str
    events: list[ComponentRuntimeEvent]


class CreateAgentSessionRequest(MedousaModel):
    args: list[str] | None = None
    command: str | None = None
    cwd: str | None = None
    prompt: str | None = None
    runtime: str = Field(
        ..., description='External runtime: `cursor` or `codex` (not `medousa`).'
    )
    session_id: str
    surface: TurnSurfaceContext | None = None


class EnvironmentPendingResponse(MedousaModel):
    pending: EnvironmentPendingProposal | None = None


class EnvironmentProposeResponse(MedousaModel):
    diffSummary: str
    errors: list[str]
    proposedSpec: EnvironmentSpec
    valid: bool


class EnvironmentSpec1(MedousaModel):
    activePresetId: str | None = None
    components: list[ComponentDef]
    layoutPresets: list[LayoutPreset] | None = None
    profileId: str
    shellChrome: ShellChromeDef | None = None
    surfaces: list[SurfaceDef]
    theme: EnvironmentTheme | None = None
    updatedAt: AwareDatetime
    updatedBy: str
    version: int = Field(..., ge=0)


class EnvironmentSpecPutRequest(MedousaModel):
    spec: EnvironmentSpec


class EnvironmentSpecResponse(MedousaModel):
    revision: int = Field(..., ge=0)
    spec: EnvironmentSpec


class EnvironmentStatusResponse(MedousaModel):
    activePresetId: str | None = None
    customSurfaces: list[CustomViewSurfaceStatus] | None = Field(
        [], validate_default=True
    )
    feedMismatchCount: int = Field(..., ge=0)
    hints: list[str] | None = []
    navOrphanCount: int = Field(..., ge=0)
    pendingProposal: bool
    profileId: str
    revision: int = Field(..., ge=0)


class EnvironmentStreamEvent(MedousaModel):
    componentPatches: list[ComponentFeedPatch] | None = None
    emittedAtUtc: AwareDatetime
    eventType: str
    feedEvent: FeedEvent | None = None
    revision: int = Field(..., ge=0)
    runtimeProbe: ComponentRuntimeProbeRequest | None = None
    spec: EnvironmentSpec | None = None


class EnvironmentValidateRequest(MedousaModel):
    spec: EnvironmentSpec


class FeedListResponse(MedousaModel):
    feeds: list[FeedListEntry]


class FeedStreamEvent(MedousaModel):
    componentPatches: list[ComponentFeedPatch] | None = None
    emittedAtUtc: AwareDatetime
    eventType: str
    feedEvent: FeedEvent | None = None
    seq: int = Field(..., ge=0)


class FeedTailResponse(MedousaModel):
    events: list[FeedEvent]
    feedId: str


class IngestRequest(MedousaModel):
    attachments: list[IngestAttachment] | None = Field(
        [],
        description='Optional attachment payloads merged into ask prompts',
        validate_default=True,
    )
    channel: str = Field(
        ..., description='Channel type identifier, e.g. "telegram", "discord", "cli"'
    )
    channel_id: str = Field(
        ...,
        description='Channel/chat/conversation identifier, e.g. "telegram:chat:67890"',
    )
    text: str = Field(
        ..., description='The text content of the message (command or prompt)'
    )
    user_id: str = Field(
        ...,
        description='User identifier within the channel, e.g. "telegram:user:12345"',
    )


class InteractiveTurnRequest(MedousaModel):
    additional_manuscript_ids: list[str] | None = None
    identity_user_id: str | None = Field(
        None,
        description='Optional identity principal override (debug/internal). Default: active workshop profile.',
    )
    manuscript_id: str | None = Field(
        None,
        description='YAML manuscript specialty for ranked digest + scheduled tool allowlist.',
    )
    max_tool_rounds: int | None = Field(
        None,
        description='When set, overrides `tui_defaults.json` for this turn (TUI live settings).',
        ge=0,
    )
    media_refs: list[MediaRef] | None = Field(
        [],
        description='User media uploaded to local medousa/media/ before this turn (P5a).',
        validate_default=True,
    )
    model: str
    persist_user_turn: bool
    prompt: str
    provider: str
    reasoning_effort: str | None = ''
    response_depth_mode: str
    retry_runtime_max_rounds: int | None = Field(None, ge=0)
    scheduled_tool_allowlist: list[str] | None = None
    session_id: str
    stage_routing: StageRoutingMatrix
    suggested_capability_ids: list[str] | None = None
    surface: TurnSurfaceContext | None = Field(
        None,
        description='Channel adapter context for ambient prompting (ingest/TUI surfaces).',
    )
    voice_appendix: str | None = None
    voice_preset_id: str | None = Field(
        None,
        description='Composer voice stance — short appendix block (not a manuscript specialty).',
    )


class InteractiveTurnStreamEvent(MedousaModel):
    agent_runtime: str | None = Field(
        None,
        description='External runtime kind when streaming an ACP session (`cursor` / `codex`).',
    )
    agent_session_id: str | None = Field(
        None,
        description='Bound Medousa chat session for agent-runtime streams (`turn_id` holds agent_session_id).',
    )
    browser_challenge_url: str | None = Field(
        None, description='URL the client should load in Agent Browser WebView.'
    )
    browser_session_id: str | None = Field(
        None, description='Agent Browser CAPTCHA / verification handoff session id.'
    )
    budget_request_id: str | None = Field(
        None,
        description='Turn budget approval pause — card id for Home deep link / notifications.',
    )
    content_delta: str | None = None
    context_usage: ContextUsageReport | None = Field(
        None,
        description='Per-layer context budget estimate (chars/4 heuristic) for operator telemetry.',
    )
    debug_message: str | None = Field(
        None,
        description='Engine/TUI telemetry — shown only when the operator opts into engine details.',
    )
    emitted_at_utc: AwareDatetime
    event_type: str
    final_text: str | None = None
    message: str
    operator_message: str | None = Field(
        None,
        description='Human-facing status whisper for rich surfaces (Home default).',
    )
    permission_request_id: str | None = Field(
        None,
        description='External ACP agent permission pause — resolve via `/v1/agents/permission-requests/{id}/approve|deny`.',
    )
    phase: str
    previous_artifact_id: str | None = Field(
        None,
        description='Previous artifact id when cognition_artifact_write supersedes a revision.',
    )
    reasoning_delta: str | None = None
    requested_rounds: int | None = Field(None, ge=0)
    root_artifact_id: str | None = Field(
        None, description='Root artifact lineage id for revision chains.'
    )
    seq: int | None = Field(
        0,
        description='Monotonic per-turn sequence number, stamped server-side by `TurnEventChannel::publish`. Enables exactly-once replay/dedup on reconnect. `#[serde(default)]` keeps the Python SDK and any older payloads (which never carried `seq`) wire-compatible.',
        ge=0,
    )
    terminal: bool
    tool_artifact_refs: list[StreamToolArtifactRef] | None = None
    tool_input_summary: str | None = None
    tool_name: str | None = None
    tool_names: list[str] | None = None
    tool_output_summary: str | None = None
    tool_round: int | None = Field(None, ge=0)
    tool_run_id: str | None = Field(
        None, description='Structured tool bus (P1) — correlates started/finished pair.'
    )
    tool_status: str | None = None
    turn_id: str
    ui_artifact: StreamUiArtifact | None = Field(
        None,
        description='Rich UI artifact presented inline in chat (cognition_ui_present).',
    )
    ui_scene: StreamUiScene | None = Field(
        None,
        description='Liquid UI scene operations (cognition_ui_scene) — model-authored structure-then-fill turns. Ops are opaque JSON validated client-side.',
    )
    work_id: str | None = Field(
        None, description='Turn worker handoff — workspace card id (`work-…`).'
    )


class JobReportResponse(MedousaModel):
    attempt_count: int = Field(..., ge=0)
    citations: list[JobCitationResponse]
    evidence_report: JobEvidenceReportResponse | None = None
    is_terminal: bool
    job_id: str
    latest_execution_id: str | None = None
    latest_outcome: str | None = None
    output_text: str | None = None
    status: str


class LocalCatalogResponse(MedousaModel):
    familyDefault: str
    models: list[CatalogModelEntry]
    recommendedModelId: str
    tier: HardwareTier
    tierLabel: str


class LocalHardwareResponse(MedousaModel):
    compiledBackends: list[str]
    engineAvailable: bool
    message: str
    profile: HardwareProfile


class LocalModelDownloadResponse(MedousaModel):
    job: ModelDownloadProgress


class LocalModelsResponse(MedousaModel):
    activeDownloads: list[ModelDownloadProgress]
    installed: list[InstalledModelRecord]


class McpGatewayStatusResponse(MedousaModel):
    gatewayUrl: str
    health: McpGatewayHealthSnapshot | None = None
    message: str
    reachable: bool
    servers: list[McpGatewayServerRuntime]


class RecurringListResponse(MedousaModel):
    count: int = Field(..., ge=0)
    recurring: list[RecurringDefinitionEntry]


class RecurringRunsResponse(MedousaModel):
    count: int = Field(..., ge=0)
    recurring_id: str
    runs: list[RecurringRunEntry]


class RuntimeConfigCommandRequest(MedousaModel):
    command: RuntimeConfigCommandSpec
    current_model: str
    current_provider: str
    current_reasoning_effort: str | None = ''
    current_response_depth_mode: str
    draft_model: str
    draft_provider: str


class RuntimeConfigCommandResponse(MedousaModel):
    next_draft_model: str
    next_draft_provider: str
    next_reasoning_effort: str
    next_response_depth_mode: str
    next_verify_policy_draft: RuntimeVerifyPolicyState | None = None
    rendered_output: str | None = None
    should_apply_settings: bool
    should_persist_depth_defaults: bool
    should_persist_reasoning_defaults: bool


class SessionAppendTurnRequest(MedousaModel):
    turn: ConversationTurn


class SessionHistoryListResponse(MedousaModel):
    next_cursor: str | None = None
    sessions: list[SessionHistorySummary]


class SessionHistoryResponse(MedousaModel):
    session_id: str
    turns: list[ConversationTurn]


class StageRouteCommandRequest(MedousaModel):
    command: StageRouteCommandSpec
    model: str
    provider: str
    stage_routing: StageRoutingMatrix


class StageRouteCommandResponse(MedousaModel):
    rendered_output: str
    stage_routing: StageRoutingMatrix


class TurnBudgetRequestListResponse(MedousaModel):
    requests: list[TurnBudgetRequestRecord]


class TurnBudgetRequestResponse(MedousaModel):
    message: str
    request: TurnBudgetRequestRecord


class VaultNoteContentResponse(MedousaModel):
    content: str
    note: VaultNote


class VaultNotesListResponse(MedousaModel):
    notes: list[VaultNote]


class VaultRootsResponse(MedousaModel):
    activeRootId: str
    roots: list[VaultRootView]


class VaultSearchResponse(MedousaModel):
    hits: list[VaultSearchHit]
    query: str


class VaultWriteResponse(MedousaModel):
    content: str | None = Field(
        None,
        description='Body actually persisted (after semantic-tag rewrite). Clients use this to stay aligned with disk instead of assuming the request body was stored.',
    )
    created: bool
    note: VaultNote


class WorkspaceCardActionResponse(MedousaModel):
    action: str
    associations: WorkCardAssociations | None = None
    card_id: str
    job_id: str | None = None
    job_succeeded: bool | None = None
    message: str
    ok: bool
    replayed: bool | None = None
    workspace_revision: int = Field(..., ge=0)


class WorkspaceStreamEvent(MedousaModel):
    card: WorkCard | None = None
    counts: dict[str, Any] | None = None
    emitted_at_utc: AwareDatetime
    feed_event: WorkspaceEvent | None = None
    snapshot: WorkspaceSnapshot | None = None
    stream_event_type: str
    workspace_revision: int = Field(..., ge=0)
