// Generated by medousa-api-contract. Do not edit.
#![allow(dead_code)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DaemonOperation {
    #[serde(rename = "admin.local_credentials.by_name.delete")]
    AdminLocalCredentialsByNameDelete,
    #[serde(rename = "admin.local_credentials.by_name.rotate.post")]
    AdminLocalCredentialsByNameRotatePost,
    #[serde(rename = "admin.local_credentials.get")]
    AdminLocalCredentialsGet,
    #[serde(rename = "agent_modes.get")]
    AgentModesGet,
    #[serde(rename = "agent_modes.policy.get")]
    AgentModesPolicyGet,
    #[serde(rename = "agent_modes.policy.put")]
    AgentModesPolicyPut,
    #[serde(rename = "agents.permission_requests.by_request_id.approve.post")]
    AgentsPermissionRequestsByRequestIdApprovePost,
    #[serde(rename = "agents.permission_requests.by_request_id.deny.post")]
    AgentsPermissionRequestsByRequestIdDenyPost,
    #[serde(rename = "agents.permission_requests.get")]
    AgentsPermissionRequestsGet,
    #[serde(rename = "agents.runtimes.get")]
    AgentsRuntimesGet,
    #[serde(rename = "agents.secret_requests.by_request_id.deny.post")]
    AgentsSecretRequestsByRequestIdDenyPost,
    #[serde(rename = "agents.secret_requests.by_request_id.fulfill.post")]
    AgentsSecretRequestsByRequestIdFulfillPost,
    #[serde(rename = "agents.secret_requests.get")]
    AgentsSecretRequestsGet,
    #[serde(rename = "agents.sessions.by_agent_session_id.cancel.post")]
    AgentsSessionsByAgentSessionIdCancelPost,
    #[serde(rename = "agents.sessions.by_agent_session_id.config.post")]
    AgentsSessionsByAgentSessionIdConfigPost,
    #[serde(rename = "agents.sessions.by_agent_session_id.prompt.post")]
    AgentsSessionsByAgentSessionIdPromptPost,
    #[serde(rename = "agents.sessions.by_agent_session_id.stream.get")]
    AgentsSessionsByAgentSessionIdStreamGet,
    #[serde(rename = "agents.sessions.post")]
    AgentsSessionsPost,
    #[serde(rename = "auth.chatgpt.begin.post")]
    AuthChatgptBeginPost,
    #[serde(rename = "auth.chatgpt.complete.post")]
    AuthChatgptCompletePost,
    #[serde(rename = "auth.chatgpt.delete")]
    AuthChatgptDelete,
    #[serde(rename = "auth.chatgpt.get")]
    AuthChatgptGet,
    #[serde(rename = "auth.chatgpt.models.get")]
    AuthChatgptModelsGet,
    #[serde(rename = "auth.chatgpt.refresh.post")]
    AuthChatgptRefreshPost,
    #[serde(rename = "bots.by_bot_id.archive.put")]
    BotsByBotIdArchivePut,
    #[serde(rename = "bots.by_bot_id.duplicate.post")]
    BotsByBotIdDuplicatePost,
    #[serde(rename = "bots.by_bot_id.get")]
    BotsByBotIdGet,
    #[serde(rename = "bots.by_bot_id.open.post")]
    BotsByBotIdOpenPost,
    #[serde(rename = "bots.by_bot_id.put")]
    BotsByBotIdPut,
    #[serde(rename = "bots.get")]
    BotsGet,
    #[serde(rename = "bots.post")]
    BotsPost,
    #[serde(rename = "browser.sessions.by_session_id.complete.post")]
    BrowserSessionsBySessionIdCompletePost,
    #[serde(rename = "browser.sessions.by_session_id.complete_act.post")]
    BrowserSessionsBySessionIdCompleteActPost,
    #[serde(rename = "browser.sessions.by_session_id.get")]
    BrowserSessionsBySessionIdGet,
    #[serde(rename = "browser.sessions.by_session_id.resume.post")]
    BrowserSessionsBySessionIdResumePost,
    #[serde(rename = "calendar.events.by_uid.delete")]
    CalendarEventsByUidDelete,
    #[serde(rename = "calendar.events.by_uid.put")]
    CalendarEventsByUidPut,
    #[serde(rename = "calendar.events.get")]
    CalendarEventsGet,
    #[serde(rename = "calendar.events.post")]
    CalendarEventsPost,
    #[serde(rename = "calendar.export.get")]
    CalendarExportGet,
    #[serde(rename = "calendar.import.post")]
    CalendarImportPost,
    #[serde(rename = "capabilities.by_capability_id.get")]
    CapabilitiesByCapabilityIdGet,
    #[serde(rename = "capabilities.get")]
    CapabilitiesGet,
    #[serde(rename = "capabilities.intents.get")]
    CapabilitiesIntentsGet,
    #[serde(rename = "capabilities.reindex.post")]
    CapabilitiesReindexPost,
    #[serde(rename = "clients.by_client_id.tools.by_request_id.result.post")]
    ClientsByClientIdToolsByRequestIdResultPost,
    #[serde(rename = "clients.by_client_id.tools.next.get")]
    ClientsByClientIdToolsNextGet,
    #[serde(rename = "clients.get")]
    ClientsGet,
    #[serde(rename = "clients.register.post")]
    ClientsRegisterPost,
    #[serde(rename = "code.capabilities.get")]
    CodeCapabilitiesGet,
    #[serde(rename = "code.conventions.get")]
    CodeConventionsGet,
    #[serde(rename = "code.definition.get")]
    CodeDefinitionGet,
    #[serde(rename = "code.diagnostics.get")]
    CodeDiagnosticsGet,
    #[serde(rename = "code.hover.get")]
    CodeHoverGet,
    #[serde(rename = "code.language_matrix.get")]
    CodeLanguageMatrixGet,
    #[serde(rename = "code.language_root.get")]
    CodeLanguageRootGet,
    #[serde(rename = "code.language_sessions.get")]
    CodeLanguageSessionsGet,
    #[serde(rename = "code.lsp.get")]
    CodeLspGet,
    #[serde(rename = "code.request.post")]
    CodeRequestPost,
    #[serde(rename = "code.symbols.get")]
    CodeSymbolsGet,
    #[serde(rename = "code.workspace_diagnostics.get")]
    CodeWorkspaceDiagnosticsGet,
    #[serde(rename = "code.workspace_symbols.get")]
    CodeWorkspaceSymbolsGet,
    #[serde(rename = "coding_engine.get")]
    CodingEngineGet,
    #[serde(rename = "components.by_component_id.runtime.events.get")]
    ComponentsByComponentIdRuntimeEventsGet,
    #[serde(rename = "components.by_component_id.runtime.events.post")]
    ComponentsByComponentIdRuntimeEventsPost,
    #[serde(rename = "components.by_component_id.runtime.probe.by_probe_id.result.post")]
    ComponentsByComponentIdRuntimeProbeByProbeIdResultPost,
    #[serde(rename = "components.by_component_id.store.by_key.delete")]
    ComponentsByComponentIdStoreByKeyDelete,
    #[serde(rename = "components.by_component_id.store.by_key.get")]
    ComponentsByComponentIdStoreByKeyGet,
    #[serde(rename = "components.by_component_id.store.by_key.put")]
    ComponentsByComponentIdStoreByKeyPut,
    #[serde(rename = "components.by_component_id.store.get")]
    ComponentsByComponentIdStoreGet,
    #[serde(rename = "components.by_component_id.store.keys.get")]
    ComponentsByComponentIdStoreKeysGet,
    #[serde(rename = "components.by_component_id.store.put")]
    ComponentsByComponentIdStorePut,
    #[serde(rename = "continuations.lineage.by_turn_correlation_id.get")]
    ContinuationsLineageByTurnCorrelationIdGet,
    #[serde(rename = "continuations.status.get")]
    ContinuationsStatusGet,
    #[serde(rename = "deliver.outbox.post")]
    DeliverOutboxPost,
    #[serde(rename = "deliver.poll.by_job_id.get")]
    DeliverPollByJobIdGet,
    #[serde(rename = "delivery.status.get")]
    DeliveryStatusGet,
    #[serde(rename = "environment.spec.get")]
    EnvironmentSpecGet,
    #[serde(rename = "environment.spec.pending.apply.post")]
    EnvironmentSpecPendingApplyPost,
    #[serde(rename = "environment.spec.pending.delete")]
    EnvironmentSpecPendingDelete,
    #[serde(rename = "environment.spec.pending.get")]
    EnvironmentSpecPendingGet,
    #[serde(rename = "environment.spec.propose.post")]
    EnvironmentSpecProposePost,
    #[serde(rename = "environment.spec.put")]
    EnvironmentSpecPut,
    #[serde(rename = "environment.spec.stream.get")]
    EnvironmentSpecStreamGet,
    #[serde(rename = "environment.spec.validate.post")]
    EnvironmentSpecValidatePost,
    #[serde(rename = "environment.status.get")]
    EnvironmentStatusGet,
    #[serde(rename = "feeds.by_feed_id.latest_good.get")]
    FeedsByFeedIdLatestGoodGet,
    #[serde(rename = "feeds.by_feed_id.read.post")]
    FeedsByFeedIdReadPost,
    #[serde(rename = "feeds.by_feed_id.tail.get")]
    FeedsByFeedIdTailGet,
    #[serde(rename = "feeds.get")]
    FeedsGet,
    #[serde(rename = "feeds.stream.get")]
    FeedsStreamGet,
    #[serde(rename = "forge.evidence.by_evidence_id.commands.get")]
    ForgeEvidenceByEvidenceIdCommandsGet,
    #[serde(rename = "forge.evidence.by_evidence_id.patch.get")]
    ForgeEvidenceByEvidenceIdPatchGet,
    #[serde(rename = "forge.evidence.by_evidence_id.receipts.get")]
    ForgeEvidenceByEvidenceIdReceiptsGet,
    #[serde(rename = "forge.items.by_work_id.apply.post")]
    ForgeItemsByWorkIdApplyPost,
    #[serde(rename = "forge.items.by_work_id.attempts.post")]
    ForgeItemsByWorkIdAttemptsPost,
    #[serde(rename = "forge.items.by_work_id.changes.blame.get")]
    ForgeItemsByWorkIdChangesBlameGet,
    #[serde(rename = "forge.items.by_work_id.changes.checkpoint.post")]
    ForgeItemsByWorkIdChangesCheckpointPost,
    #[serde(rename = "forge.items.by_work_id.changes.conflict.post")]
    ForgeItemsByWorkIdChangesConflictPost,
    #[serde(rename = "forge.items.by_work_id.changes.fetch.post")]
    ForgeItemsByWorkIdChangesFetchPost,
    #[serde(rename = "forge.items.by_work_id.changes.file.get")]
    ForgeItemsByWorkIdChangesFileGet,
    #[serde(rename = "forge.items.by_work_id.changes.file.hunk.post")]
    ForgeItemsByWorkIdChangesFileHunkPost,
    #[serde(rename = "forge.items.by_work_id.changes.file.post")]
    ForgeItemsByWorkIdChangesFilePost,
    #[serde(rename = "forge.items.by_work_id.changes.get")]
    ForgeItemsByWorkIdChangesGet,
    #[serde(rename = "forge.items.by_work_id.changes.history.get")]
    ForgeItemsByWorkIdChangesHistoryGet,
    #[serde(rename = "forge.items.by_work_id.changes.pull.post")]
    ForgeItemsByWorkIdChangesPullPost,
    #[serde(rename = "forge.items.by_work_id.changes.push.post")]
    ForgeItemsByWorkIdChangesPushPost,
    #[serde(rename = "forge.items.by_work_id.changes.sync.post")]
    ForgeItemsByWorkIdChangesSyncPost,
    #[serde(rename = "forge.items.by_work_id.decisions.post")]
    ForgeItemsByWorkIdDecisionsPost,
    #[serde(rename = "forge.items.by_work_id.discard.post")]
    ForgeItemsByWorkIdDiscardPost,
    #[serde(rename = "forge.items.by_work_id.export.post")]
    ForgeItemsByWorkIdExportPost,
    #[serde(rename = "forge.items.by_work_id.get")]
    ForgeItemsByWorkIdGet,
    #[serde(rename = "forge.items.by_work_id.handoff.post")]
    ForgeItemsByWorkIdHandoffPost,
    #[serde(rename = "forge.items.by_work_id.project_events.get")]
    ForgeItemsByWorkIdProjectEventsGet,
    #[serde(rename = "forge.items.by_work_id.provider.comments.get")]
    ForgeItemsByWorkIdProviderCommentsGet,
    #[serde(rename = "forge.items.by_work_id.provider.comments.post")]
    ForgeItemsByWorkIdProviderCommentsPost,
    #[serde(rename = "forge.items.by_work_id.provider.context.put")]
    ForgeItemsByWorkIdProviderContextPut,
    #[serde(rename = "forge.items.by_work_id.provider.get")]
    ForgeItemsByWorkIdProviderGet,
    #[serde(rename = "forge.items.by_work_id.provider.post")]
    ForgeItemsByWorkIdProviderPost,
    #[serde(rename = "forge.items.by_work_id.provision.post")]
    ForgeItemsByWorkIdProvisionPost,
    #[serde(rename = "forge.items.by_work_id.review.comments.by_comment_id.delete")]
    ForgeItemsByWorkIdReviewCommentsByCommentIdDelete,
    #[serde(rename = "forge.items.by_work_id.review.comments.by_comment_id.patch")]
    ForgeItemsByWorkIdReviewCommentsByCommentIdPatch,
    #[serde(rename = "forge.items.by_work_id.review.comments.get")]
    ForgeItemsByWorkIdReviewCommentsGet,
    #[serde(rename = "forge.items.by_work_id.review.comments.post")]
    ForgeItemsByWorkIdReviewCommentsPost,
    #[serde(rename = "forge.items.by_work_id.review.continue_editing.post")]
    ForgeItemsByWorkIdReviewContinueEditingPost,
    #[serde(rename = "forge.items.by_work_id.review.file.get")]
    ForgeItemsByWorkIdReviewFileGet,
    #[serde(rename = "forge.items.by_work_id.review.file.post")]
    ForgeItemsByWorkIdReviewFilePost,
    #[serde(rename = "forge.items.by_work_id.review.get")]
    ForgeItemsByWorkIdReviewGet,
    #[serde(rename = "forge.items.by_work_id.review.request_changes.post")]
    ForgeItemsByWorkIdReviewRequestChangesPost,
    #[serde(rename = "forge.items.by_work_id.run_script.post")]
    ForgeItemsByWorkIdRunScriptPost,
    #[serde(rename = "forge.items.by_work_id.search.get")]
    ForgeItemsByWorkIdSearchGet,
    #[serde(rename = "forge.items.by_work_id.search.replace.post")]
    ForgeItemsByWorkIdSearchReplacePost,
    #[serde(rename = "forge.items.by_work_id.source.batch.put")]
    ForgeItemsByWorkIdSourceBatchPut,
    #[serde(rename = "forge.items.by_work_id.source.delete")]
    ForgeItemsByWorkIdSourceDelete,
    #[serde(rename = "forge.items.by_work_id.source.get")]
    ForgeItemsByWorkIdSourceGet,
    #[serde(rename = "forge.items.by_work_id.source.patch")]
    ForgeItemsByWorkIdSourcePatch,
    #[serde(rename = "forge.items.by_work_id.source.post")]
    ForgeItemsByWorkIdSourcePost,
    #[serde(rename = "forge.items.by_work_id.source.put")]
    ForgeItemsByWorkIdSourcePut,
    #[serde(rename = "forge.items.by_work_id.source.workspace_edit.put")]
    ForgeItemsByWorkIdSourceWorkspaceEditPut,
    #[serde(rename = "forge.items.by_work_id.task_runs.by_run_id.delete")]
    ForgeItemsByWorkIdTaskRunsByRunIdDelete,
    #[serde(rename = "forge.items.by_work_id.task_runs.by_run_id.events.get")]
    ForgeItemsByWorkIdTaskRunsByRunIdEventsGet,
    #[serde(rename = "forge.items.by_work_id.task_runs.by_run_id.get")]
    ForgeItemsByWorkIdTaskRunsByRunIdGet,
    #[serde(rename = "forge.items.by_work_id.task_runs.by_run_id.preview.post")]
    ForgeItemsByWorkIdTaskRunsByRunIdPreviewPost,
    #[serde(rename = "forge.items.by_work_id.task_runs.get")]
    ForgeItemsByWorkIdTaskRunsGet,
    #[serde(rename = "forge.items.by_work_id.tasks.by_task_id.run.post")]
    ForgeItemsByWorkIdTasksByTaskIdRunPost,
    #[serde(rename = "forge.items.by_work_id.tasks.by_task_id.runs.post")]
    ForgeItemsByWorkIdTasksByTaskIdRunsPost,
    #[serde(rename = "forge.items.by_work_id.tasks.get")]
    ForgeItemsByWorkIdTasksGet,
    #[serde(rename = "forge.items.by_work_id.tests.get")]
    ForgeItemsByWorkIdTestsGet,
    #[serde(rename = "forge.items.by_work_id.tree.get")]
    ForgeItemsByWorkIdTreeGet,
    #[serde(rename = "forge.items.by_work_id.workspace_state.get")]
    ForgeItemsByWorkIdWorkspaceStateGet,
    #[serde(rename = "forge.items.by_work_id.workspace_state.put")]
    ForgeItemsByWorkIdWorkspaceStatePut,
    #[serde(rename = "forge.items.get")]
    ForgeItemsGet,
    #[serde(rename = "forge.items.post")]
    ForgeItemsPost,
    #[serde(rename = "forge.items.start.post")]
    ForgeItemsStartPost,
    #[serde(rename = "forge.leases.by_lease_id.complete.post")]
    ForgeLeasesByLeaseIdCompletePost,
    #[serde(rename = "forge.leases.by_lease_id.fail.post")]
    ForgeLeasesByLeaseIdFailPost,
    #[serde(rename = "forge.leases.by_lease_id.heartbeat.post")]
    ForgeLeasesByLeaseIdHeartbeatPost,
    #[serde(rename = "forge.leases.by_lease_id.interrupt.post")]
    ForgeLeasesByLeaseIdInterruptPost,
    #[serde(rename = "forge.preview.by_token.by_rest.delete")]
    ForgePreviewByTokenByRestDelete,
    #[serde(rename = "forge.preview.by_token.by_rest.get")]
    ForgePreviewByTokenByRestGet,
    #[serde(rename = "forge.preview.by_token.by_rest.head")]
    ForgePreviewByTokenByRestHead,
    #[serde(rename = "forge.preview.by_token.by_rest.options")]
    ForgePreviewByTokenByRestOptions,
    #[serde(rename = "forge.preview.by_token.by_rest.patch")]
    ForgePreviewByTokenByRestPatch,
    #[serde(rename = "forge.preview.by_token.by_rest.post")]
    ForgePreviewByTokenByRestPost,
    #[serde(rename = "forge.preview.by_token.by_rest.put")]
    ForgePreviewByTokenByRestPut,
    #[serde(rename = "forge.preview.by_token.delete")]
    ForgePreviewByTokenDelete,
    #[serde(rename = "forge.preview.by_token.get")]
    ForgePreviewByTokenGet,
    #[serde(rename = "forge.preview.by_token.head")]
    ForgePreviewByTokenHead,
    #[serde(rename = "forge.preview.by_token.options")]
    ForgePreviewByTokenOptions,
    #[serde(rename = "forge.preview.by_token.patch")]
    ForgePreviewByTokenPatch,
    #[serde(rename = "forge.preview.by_token.post")]
    ForgePreviewByTokenPost,
    #[serde(rename = "forge.preview.by_token.put")]
    ForgePreviewByTokenPut,
    #[serde(rename = "forge.repositories.browse.get")]
    ForgeRepositoriesBrowseGet,
    #[serde(rename = "forge.repositories.get")]
    ForgeRepositoriesGet,
    #[serde(rename = "forge.repositories.inspect.post")]
    ForgeRepositoriesInspectPost,
    #[serde(rename = "forge.repositories.provider.get")]
    ForgeRepositoriesProviderGet,
    #[serde(rename = "forge.repositories.provider.post")]
    ForgeRepositoriesProviderPost,
    #[serde(rename = "forge.repositories.put")]
    ForgeRepositoriesPut,
    #[serde(rename = "forge.stream.get")]
    ForgeStreamGet,
    #[serde(rename = "grapheme.allowlist.get")]
    GraphemeAllowlistGet,
    #[serde(rename = "grapheme.allowlist.put")]
    GraphemeAllowlistPut,
    #[serde(rename = "grapheme.compile.post")]
    GraphemeCompilePost,
    #[serde(rename = "grapheme.lifecycle.get")]
    GraphemeLifecycleGet,
    #[serde(rename = "grapheme.lsp.get")]
    GraphemeLspGet,
    #[serde(rename = "grapheme.lsp.workspace.get")]
    GraphemeLspWorkspaceGet,
    #[serde(rename = "grapheme.modules.by_module_id.get")]
    GraphemeModulesByModuleIdGet,
    #[serde(rename = "grapheme.modules.by_module_id.ops.get")]
    GraphemeModulesByModuleIdOpsGet,
    #[serde(rename = "grapheme.modules.get")]
    GraphemeModulesGet,
    #[serde(rename = "grapheme.modules.load.post")]
    GraphemeModulesLoadPost,
    #[serde(rename = "grapheme.run.post")]
    GraphemeRunPost,
    #[serde(rename = "grapheme.scripts.by_script_id.delete")]
    GraphemeScriptsByScriptIdDelete,
    #[serde(rename = "grapheme.scripts.by_script_id.get")]
    GraphemeScriptsByScriptIdGet,
    #[serde(rename = "grapheme.scripts.by_script_id.rename.post")]
    GraphemeScriptsByScriptIdRenamePost,
    #[serde(rename = "grapheme.scripts.get")]
    GraphemeScriptsGet,
    #[serde(rename = "grapheme.scripts.post")]
    GraphemeScriptsPost,
    #[serde(rename = "health.get")]
    HealthGet,
    #[serde(rename = "heartbeat.status.get")]
    HeartbeatStatusGet,
    #[serde(rename = "identity.context.post")]
    IdentityContextPost,
    #[serde(rename = "identity.digest_preview.post")]
    IdentityDigestPreviewPost,
    #[serde(rename = "identity.export_markdown.post")]
    IdentityExportMarkdownPost,
    #[serde(rename = "identity.history.post")]
    IdentityHistoryPost,
    #[serde(rename = "identity.profiles.active.put")]
    IdentityProfilesActivePut,
    #[serde(rename = "identity.profiles.export.post")]
    IdentityProfilesExportPost,
    #[serde(rename = "identity.profiles.get")]
    IdentityProfilesGet,
    #[serde(rename = "identity.profiles.import.post")]
    IdentityProfilesImportPost,
    #[serde(rename = "identity.profiles.post")]
    IdentityProfilesPost,
    #[serde(rename = "identity.remember.post")]
    IdentityRememberPost,
    #[serde(rename = "identity.rollback.post")]
    IdentityRollbackPost,
    #[serde(rename = "identity.update.commit.post")]
    IdentityUpdateCommitPost,
    #[serde(rename = "identity.update.propose.post")]
    IdentityUpdateProposePost,
    #[serde(rename = "ingest.by_stream_id.stream.get")]
    IngestByStreamIdStreamGet,
    #[serde(rename = "ingest.post")]
    IngestPost,
    #[serde(rename = "integrations.by_connection_id.delete")]
    IntegrationsByConnectionIdDelete,
    #[serde(rename = "integrations.by_connection_id.get")]
    IntegrationsByConnectionIdGet,
    #[serde(rename = "integrations.by_connection_id.patch")]
    IntegrationsByConnectionIdPatch,
    #[serde(rename = "integrations.by_connection_id.secrets.by_slot.delete")]
    IntegrationsByConnectionIdSecretsBySlotDelete,
    #[serde(rename = "integrations.by_connection_id.secrets.by_slot.put")]
    IntegrationsByConnectionIdSecretsBySlotPut,
    #[serde(rename = "integrations.get")]
    IntegrationsGet,
    #[serde(rename = "integrations.post")]
    IntegrationsPost,
    #[serde(rename = "interactive.turn.by_turn_id.stream.get")]
    InteractiveTurnByTurnIdStreamGet,
    #[serde(rename = "interactive.turn.post")]
    InteractiveTurnPost,
    #[serde(rename = "jobs.ask.post")]
    JobsAskPost,
    #[serde(rename = "jobs.by_job_id.archive.post")]
    JobsByJobIdArchivePost,
    #[serde(rename = "jobs.by_job_id.complete_actions.post")]
    JobsByJobIdCompleteActionsPost,
    #[serde(rename = "jobs.by_job_id.replay_and_resume.post")]
    JobsByJobIdReplayAndResumePost,
    #[serde(rename = "jobs.by_job_id.report.get")]
    JobsByJobIdReportGet,
    #[serde(rename = "jobs.by_job_id.result.get")]
    JobsByJobIdResultGet,
    #[serde(rename = "jobs.prompt.post")]
    JobsPromptPost,
    #[serde(rename = "jobs.report.post")]
    JobsReportPost,
    #[serde(rename = "lan.workshops.get")]
    LanWorkshopsGet,
    #[serde(rename = "liveness.get")]
    LivenessGet,
    #[serde(rename = "local.catalog.get")]
    LocalCatalogGet,
    #[serde(rename = "local.engine.status.get")]
    LocalEngineStatusGet,
    #[serde(rename = "local.hardware.get")]
    LocalHardwareGet,
    #[serde(rename = "local.models.by_model_id.delete")]
    LocalModelsByModelIdDelete,
    #[serde(rename = "local.models.download.by_job_id.events.get")]
    LocalModelsDownloadByJobIdEventsGet,
    #[serde(rename = "local.models.download.by_job_id.get")]
    LocalModelsDownloadByJobIdGet,
    #[serde(rename = "local.models.download.post")]
    LocalModelsDownloadPost,
    #[serde(rename = "local.models.get")]
    LocalModelsGet,
    #[serde(rename = "locus.nodes.by_sync_key.get")]
    LocusNodesBySyncKeyGet,
    #[serde(rename = "locus.nodes.get")]
    LocusNodesGet,
    #[serde(rename = "locus.tags.get")]
    LocusTagsGet,
    #[serde(rename = "maintenance.artifacts.get")]
    MaintenanceArtifactsGet,
    #[serde(rename = "maintenance.artifacts.put")]
    MaintenanceArtifactsPut,
    #[serde(rename = "maintenance.storage.get")]
    MaintenanceStorageGet,
    #[serde(rename = "maintenance.storage.post")]
    MaintenanceStoragePost,
    #[serde(rename = "maintenance.storage.put")]
    MaintenanceStoragePut,
    #[serde(rename = "manuscripts.by_manuscript_id.get")]
    ManuscriptsByManuscriptIdGet,
    #[serde(rename = "manuscripts.by_manuscript_id.patch")]
    ManuscriptsByManuscriptIdPatch,
    #[serde(rename = "manuscripts.create.post")]
    ManuscriptsCreatePost,
    #[serde(rename = "manuscripts.get")]
    ManuscriptsGet,
    #[serde(rename = "manuscripts.post")]
    ManuscriptsPost,
    #[serde(rename = "mcp.gateway.status.get")]
    McpGatewayStatusGet,
    #[serde(rename = "mcp.oauth.begin.post")]
    McpOauthBeginPost,
    #[serde(rename = "mcp.oauth.by_server_id.delete")]
    McpOauthByServerIdDelete,
    #[serde(rename = "mcp.oauth.by_server_id.get")]
    McpOauthByServerIdGet,
    #[serde(rename = "mcp.oauth.complete.post")]
    McpOauthCompletePost,
    #[serde(rename = "mcp.oauth.refresh.post")]
    McpOauthRefreshPost,
    #[serde(rename = "mcp.policy.evaluate.post")]
    McpPolicyEvaluatePost,
    #[serde(rename = "media.by_media_id.get")]
    MediaByMediaIdGet,
    #[serde(rename = "media.upload.post")]
    MediaUploadPost,
    #[serde(rename = "mesh.inbox.get")]
    MeshInboxGet,
    #[serde(rename = "mesh.intros.by_intro_id.accept.post")]
    MeshIntrosByIntroIdAcceptPost,
    #[serde(rename = "mesh.intros.by_intro_id.decline.post")]
    MeshIntrosByIntroIdDeclinePost,
    #[serde(rename = "mesh.intros.candidates.get")]
    MeshIntrosCandidatesGet,
    #[serde(rename = "mesh.intros.get")]
    MeshIntrosGet,
    #[serde(rename = "mesh.intros.post")]
    MeshIntrosPost,
    #[serde(rename = "mesh.outbox.by_item_id.flush.post")]
    MeshOutboxByItemIdFlushPost,
    #[serde(rename = "mesh.outbox.get")]
    MeshOutboxGet,
    #[serde(rename = "mesh.outbox.post")]
    MeshOutboxPost,
    #[serde(rename = "mesh.peers.by_device_id.patch")]
    MeshPeersByDeviceIdPatch,
    #[serde(rename = "mesh.peers.get")]
    MeshPeersGet,
    #[serde(rename = "mesh.receipts.get")]
    MeshReceiptsGet,
    #[serde(rename = "mesh.receipts.post")]
    MeshReceiptsPost,
    #[serde(rename = "mesh.tasks.by_work_id.control.post")]
    MeshTasksByWorkIdControlPost,
    #[serde(rename = "mesh.tasks.post")]
    MeshTasksPost,
    #[serde(rename = "models.capabilities.get")]
    ModelsCapabilitiesGet,
    #[serde(rename = "models.catalog.get")]
    ModelsCatalogGet,
    #[serde(rename = "models.catalog.refresh.post")]
    ModelsCatalogRefreshPost,
    #[serde(rename = "pair.by_pairing_id.delete")]
    PairByPairingIdDelete,
    #[serde(rename = "pair.by_pairing_id.policy.put")]
    PairByPairingIdPolicyPut,
    #[serde(rename = "pair.code.get")]
    PairCodeGet,
    #[serde(rename = "pair.heartbeat.get")]
    PairHeartbeatGet,
    #[serde(rename = "pair.heartbeat.post")]
    PairHeartbeatPost,
    #[serde(rename = "pair.init.post")]
    PairInitPost,
    #[serde(rename = "pair.iroh_ticket.get")]
    PairIrohTicketGet,
    #[serde(rename = "pair.session.challenge.post")]
    PairSessionChallengePost,
    #[serde(rename = "pair.session.refresh.post")]
    PairSessionRefreshPost,
    #[serde(rename = "pair.status.get")]
    PairStatusGet,
    #[serde(rename = "pair.verify.post")]
    PairVerifyPost,
    #[serde(rename = "peer.messages.by_message_id.read.post")]
    PeerMessagesByMessageIdReadPost,
    #[serde(rename = "peer.messages.get")]
    PeerMessagesGet,
    #[serde(rename = "peer.messages.post")]
    PeerMessagesPost,
    #[serde(rename = "peer.messages.unread_count.get")]
    PeerMessagesUnreadCountGet,
    #[serde(rename = "peers.by_device_id.execution_policy.get")]
    PeersByDeviceIdExecutionPolicyGet,
    #[serde(rename = "peers.by_device_id.execution_policy.put")]
    PeersByDeviceIdExecutionPolicyPut,
    #[serde(rename = "peers.execution_policies.get")]
    PeersExecutionPoliciesGet,
    #[serde(rename = "peers.execution_policy_audit.get")]
    PeersExecutionPolicyAuditGet,
    #[serde(rename = "prompt_stashes.by_stash_id.delete")]
    PromptStashesByStashIdDelete,
    #[serde(rename = "prompt_stashes.get")]
    PromptStashesGet,
    #[serde(rename = "prompt_stashes.post")]
    PromptStashesPost,
    #[serde(rename = "qr.get")]
    QrGet,
    #[serde(rename = "qr.image.get")]
    QrImageGet,
    #[serde(rename = "qr.png.get")]
    QrPngGet,
    #[serde(rename = "qr.rotate.post")]
    QrRotatePost,
    #[serde(rename = "recurring.by_recurring_id.delete")]
    RecurringByRecurringIdDelete,
    #[serde(rename = "recurring.by_recurring_id.delivery.get")]
    RecurringByRecurringIdDeliveryGet,
    #[serde(rename = "recurring.by_recurring_id.patch")]
    RecurringByRecurringIdPatch,
    #[serde(rename = "recurring.by_recurring_id.runs.get")]
    RecurringByRecurringIdRunsGet,
    #[serde(rename = "recurring.get")]
    RecurringGet,
    #[serde(rename = "recurring.prompt.post")]
    RecurringPromptPost,
    #[serde(rename = "runtime.artifact.command.post")]
    RuntimeArtifactCommandPost,
    #[serde(rename = "runtime.artifact.delete.post")]
    RuntimeArtifactDeletePost,
    #[serde(rename = "runtime.artifact.fetch.post")]
    RuntimeArtifactFetchPost,
    #[serde(rename = "runtime.artifact.list_ui.post")]
    RuntimeArtifactListUiPost,
    #[serde(rename = "runtime.artifact.write.post")]
    RuntimeArtifactWritePost,
    #[serde(rename = "runtime.config.command.post")]
    RuntimeConfigCommandPost,
    #[serde(rename = "runtime.defaults.get")]
    RuntimeDefaultsGet,
    #[serde(rename = "runtime.inference_profiles.put")]
    RuntimeInferenceProfilesPut,
    #[serde(rename = "runtime.stage_route.command.post")]
    RuntimeStageRouteCommandPost,
    #[serde(rename = "runtime.tui_defaults.get")]
    RuntimeTuiDefaultsGet,
    #[serde(rename = "runtime.tui_defaults.put")]
    RuntimeTuiDefaultsPut,
    #[serde(rename = "runtime.workers.get")]
    RuntimeWorkersGet,
    #[serde(rename = "runtime.workers.put")]
    RuntimeWorkersPut,
    #[serde(rename = "session_deletions.by_deletion_id.get")]
    SessionDeletionsByDeletionIdGet,
    #[serde(rename = "sessions.by_session_id.active_turn.get")]
    SessionsBySessionIdActiveTurnGet,
    #[serde(rename = "sessions.by_session_id.active_turn.post")]
    SessionsBySessionIdActiveTurnPost,
    #[serde(rename = "sessions.by_session_id.agent_mode.delete")]
    SessionsBySessionIdAgentModeDelete,
    #[serde(rename = "sessions.by_session_id.agent_mode.get")]
    SessionsBySessionIdAgentModeGet,
    #[serde(rename = "sessions.by_session_id.agent_mode.proposals.by_proposal_id.put")]
    SessionsBySessionIdAgentModeProposalsByProposalIdPut,
    #[serde(rename = "sessions.by_session_id.agent_mode.proposals.get")]
    SessionsBySessionIdAgentModeProposalsGet,
    #[serde(rename = "sessions.by_session_id.agent_mode.put")]
    SessionsBySessionIdAgentModePut,
    #[serde(rename = "sessions.by_session_id.bot.delete")]
    SessionsBySessionIdBotDelete,
    #[serde(rename = "sessions.by_session_id.bot.get")]
    SessionsBySessionIdBotGet,
    #[serde(rename = "sessions.by_session_id.bot.put")]
    SessionsBySessionIdBotPut,
    #[serde(rename = "sessions.by_session_id.code_binding.delete")]
    SessionsBySessionIdCodeBindingDelete,
    #[serde(rename = "sessions.by_session_id.code_binding.get")]
    SessionsBySessionIdCodeBindingGet,
    #[serde(rename = "sessions.by_session_id.code_binding.put")]
    SessionsBySessionIdCodeBindingPut,
    #[serde(rename = "sessions.by_session_id.code_project.post")]
    SessionsBySessionIdCodeProjectPost,
    #[serde(rename = "sessions.by_session_id.delete")]
    SessionsBySessionIdDelete,
    #[serde(rename = "sessions.by_session_id.history.get")]
    SessionsBySessionIdHistoryGet,
    #[serde(rename = "sessions.by_session_id.name.put")]
    SessionsBySessionIdNamePut,
    #[serde(rename = "sessions.by_session_id.turns.get")]
    SessionsBySessionIdTurnsGet,
    #[serde(rename = "sessions.by_session_id.turns.post")]
    SessionsBySessionIdTurnsPost,
    #[serde(rename = "sessions.by_session_id.workshop.steer.post")]
    SessionsBySessionIdWorkshopSteerPost,
    #[serde(rename = "sessions.derive.post")]
    SessionsDerivePost,
    #[serde(rename = "sessions.get")]
    SessionsGet,
    #[serde(rename = "sessions.post")]
    SessionsPost,
    #[serde(rename = "sessions.search.get")]
    SessionsSearchGet,
    #[serde(rename = "sessions.shell.by_id.get")]
    SessionsShellByIdGet,
    #[serde(rename = "sessions.shell.by_id.signal.post")]
    SessionsShellByIdSignalPost,
    #[serde(rename = "sessions.shell.get")]
    SessionsShellGet,
    #[serde(rename = "sessions.shell.post")]
    SessionsShellPost,
    #[serde(rename = "share.capabilities.get")]
    ShareCapabilitiesGet,
    #[serde(rename = "share.export.post")]
    ShareExportPost,
    #[serde(rename = "share.import.post")]
    ShareImportPost,
    #[serde(rename = "share.push.post")]
    SharePushPost,
    #[serde(rename = "shared_mode.get")]
    SharedModeGet,
    #[serde(rename = "shared_mode.put")]
    SharedModePut,
    #[serde(rename = "shell_sessions.get")]
    ShellSessionsGet,
    #[serde(rename = "stats.get")]
    StatsGet,
    #[serde(rename = "stt.status.get")]
    SttStatusGet,
    #[serde(rename = "stt.transcribe.post")]
    SttTranscribePost,
    #[serde(rename = "tool_history.slices.get")]
    ToolHistorySlicesGet,
    #[serde(rename = "turns.budget_requests.by_request_id.approve.post")]
    TurnsBudgetRequestsByRequestIdApprovePost,
    #[serde(rename = "turns.budget_requests.by_request_id.deny.post")]
    TurnsBudgetRequestsByRequestIdDenyPost,
    #[serde(rename = "turns.budget_requests.by_request_id.get")]
    TurnsBudgetRequestsByRequestIdGet,
    #[serde(rename = "turns.budget_requests.get")]
    TurnsBudgetRequestsGet,
    #[serde(rename = "turns.by_turn_id.get")]
    TurnsByTurnIdGet,
    #[serde(rename = "turns.post")]
    TurnsPost,
    #[serde(rename = "vault.active.put")]
    VaultActivePut,
    #[serde(rename = "vault.backlinks.get")]
    VaultBacklinksGet,
    #[serde(rename = "vault.changes.get")]
    VaultChangesGet,
    #[serde(rename = "vault.files.by_file_path.get")]
    VaultFilesByFilePathGet,
    #[serde(rename = "vault.git.commit.post")]
    VaultGitCommitPost,
    #[serde(rename = "vault.git.detect.get")]
    VaultGitDetectGet,
    #[serde(rename = "vault.git.diff.get")]
    VaultGitDiffGet,
    #[serde(rename = "vault.git.enable.post")]
    VaultGitEnablePost,
    #[serde(rename = "vault.git.init.post")]
    VaultGitInitPost,
    #[serde(rename = "vault.git.install.post")]
    VaultGitInstallPost,
    #[serde(rename = "vault.git.log.get")]
    VaultGitLogGet,
    #[serde(rename = "vault.git.restore.post")]
    VaultGitRestorePost,
    #[serde(rename = "vault.git.status.get")]
    VaultGitStatusGet,
    #[serde(rename = "vault.git.worktrees.get")]
    VaultGitWorktreesGet,
    #[serde(rename = "vault.notes.by_note_path.delete")]
    VaultNotesByNotePathDelete,
    #[serde(rename = "vault.notes.by_note_path.get")]
    VaultNotesByNotePathGet,
    #[serde(rename = "vault.notes.by_note_path.put")]
    VaultNotesByNotePathPut,
    #[serde(rename = "vault.notes.get")]
    VaultNotesGet,
    #[serde(rename = "vault.notes.post")]
    VaultNotesPost,
    #[serde(rename = "vault.roots.get")]
    VaultRootsGet,
    #[serde(rename = "vault.roots.post")]
    VaultRootsPost,
    #[serde(rename = "vault.search.get")]
    VaultSearchGet,
    #[serde(rename = "vault.tags.get")]
    VaultTagsGet,
    #[serde(rename = "vault.trash.get")]
    VaultTrashGet,
    #[serde(rename = "vault.trash.restore.post")]
    VaultTrashRestorePost,
    #[serde(rename = "workflows.by_workflow_id.get")]
    WorkflowsByWorkflowIdGet,
    #[serde(rename = "workflows.by_workflow_id.runs.get")]
    WorkflowsByWorkflowIdRunsGet,
    #[serde(rename = "workflows.from_slice.post")]
    WorkflowsFromSlicePost,
    #[serde(rename = "workflows.get")]
    WorkflowsGet,
    #[serde(rename = "workflows.plan.post")]
    WorkflowsPlanPost,
    #[serde(rename = "workflows.post")]
    WorkflowsPost,
    #[serde(rename = "workflows.schedule.post")]
    WorkflowsSchedulePost,
    #[serde(rename = "workspace.cards.by_card_id.archive.post")]
    WorkspaceCardsByCardIdArchivePost,
    #[serde(rename = "workspace.cards.by_card_id.cancel.post")]
    WorkspaceCardsByCardIdCancelPost,
    #[serde(rename = "workspace.cards.by_card_id.get")]
    WorkspaceCardsByCardIdGet,
    #[serde(rename = "workspace.cards.by_card_id.link_vault.post")]
    WorkspaceCardsByCardIdLinkVaultPost,
    #[serde(rename = "workspace.cards.by_card_id.retry.post")]
    WorkspaceCardsByCardIdRetryPost,
    #[serde(rename = "workspace.cards.get")]
    WorkspaceCardsGet,
    #[serde(rename = "workspace.feed.get")]
    WorkspaceFeedGet,
    #[serde(rename = "workspace.rebuild.post")]
    WorkspaceRebuildPost,
    #[serde(rename = "workspace.snapshot.get")]
    WorkspaceSnapshotGet,
    #[serde(rename = "workspace.stream.get")]
    WorkspaceStreamGet,
    #[serde(rename = "world.at_location.get")]
    WorldAtLocationGet,
    #[serde(rename = "world.bindings.by_work_id.get")]
    WorldBindingsByWorkIdGet,
    #[serde(rename = "world.code_avec.get")]
    WorldCodeAvecGet,
    #[serde(rename = "world.files.get")]
    WorldFilesGet,
    #[serde(rename = "world.find.get")]
    WorldFindGet,
    #[serde(rename = "world.get")]
    WorldGet,
    #[serde(rename = "world.impact.get")]
    WorldImpactGet,
    #[serde(rename = "world.index.post")]
    WorldIndexPost,
    #[serde(rename = "world.reset_store.post")]
    WorldResetStorePost,
    #[serde(rename = "world.status.get")]
    WorldStatusGet,
}

impl DaemonOperation {
    pub fn id(self) -> &'static str {
        match self {
            Self::AdminLocalCredentialsByNameDelete => "admin.local_credentials.by_name.delete",
            Self::AdminLocalCredentialsByNameRotatePost => "admin.local_credentials.by_name.rotate.post",
            Self::AdminLocalCredentialsGet => "admin.local_credentials.get",
            Self::AgentModesGet => "agent_modes.get",
            Self::AgentModesPolicyGet => "agent_modes.policy.get",
            Self::AgentModesPolicyPut => "agent_modes.policy.put",
            Self::AgentsPermissionRequestsByRequestIdApprovePost => "agents.permission_requests.by_request_id.approve.post",
            Self::AgentsPermissionRequestsByRequestIdDenyPost => "agents.permission_requests.by_request_id.deny.post",
            Self::AgentsPermissionRequestsGet => "agents.permission_requests.get",
            Self::AgentsRuntimesGet => "agents.runtimes.get",
            Self::AgentsSecretRequestsByRequestIdDenyPost => "agents.secret_requests.by_request_id.deny.post",
            Self::AgentsSecretRequestsByRequestIdFulfillPost => "agents.secret_requests.by_request_id.fulfill.post",
            Self::AgentsSecretRequestsGet => "agents.secret_requests.get",
            Self::AgentsSessionsByAgentSessionIdCancelPost => "agents.sessions.by_agent_session_id.cancel.post",
            Self::AgentsSessionsByAgentSessionIdConfigPost => "agents.sessions.by_agent_session_id.config.post",
            Self::AgentsSessionsByAgentSessionIdPromptPost => "agents.sessions.by_agent_session_id.prompt.post",
            Self::AgentsSessionsByAgentSessionIdStreamGet => "agents.sessions.by_agent_session_id.stream.get",
            Self::AgentsSessionsPost => "agents.sessions.post",
            Self::AuthChatgptBeginPost => "auth.chatgpt.begin.post",
            Self::AuthChatgptCompletePost => "auth.chatgpt.complete.post",
            Self::AuthChatgptDelete => "auth.chatgpt.delete",
            Self::AuthChatgptGet => "auth.chatgpt.get",
            Self::AuthChatgptModelsGet => "auth.chatgpt.models.get",
            Self::AuthChatgptRefreshPost => "auth.chatgpt.refresh.post",
            Self::BotsByBotIdArchivePut => "bots.by_bot_id.archive.put",
            Self::BotsByBotIdDuplicatePost => "bots.by_bot_id.duplicate.post",
            Self::BotsByBotIdGet => "bots.by_bot_id.get",
            Self::BotsByBotIdOpenPost => "bots.by_bot_id.open.post",
            Self::BotsByBotIdPut => "bots.by_bot_id.put",
            Self::BotsGet => "bots.get",
            Self::BotsPost => "bots.post",
            Self::BrowserSessionsBySessionIdCompletePost => "browser.sessions.by_session_id.complete.post",
            Self::BrowserSessionsBySessionIdCompleteActPost => "browser.sessions.by_session_id.complete_act.post",
            Self::BrowserSessionsBySessionIdGet => "browser.sessions.by_session_id.get",
            Self::BrowserSessionsBySessionIdResumePost => "browser.sessions.by_session_id.resume.post",
            Self::CalendarEventsByUidDelete => "calendar.events.by_uid.delete",
            Self::CalendarEventsByUidPut => "calendar.events.by_uid.put",
            Self::CalendarEventsGet => "calendar.events.get",
            Self::CalendarEventsPost => "calendar.events.post",
            Self::CalendarExportGet => "calendar.export.get",
            Self::CalendarImportPost => "calendar.import.post",
            Self::CapabilitiesByCapabilityIdGet => "capabilities.by_capability_id.get",
            Self::CapabilitiesGet => "capabilities.get",
            Self::CapabilitiesIntentsGet => "capabilities.intents.get",
            Self::CapabilitiesReindexPost => "capabilities.reindex.post",
            Self::ClientsByClientIdToolsByRequestIdResultPost => "clients.by_client_id.tools.by_request_id.result.post",
            Self::ClientsByClientIdToolsNextGet => "clients.by_client_id.tools.next.get",
            Self::ClientsGet => "clients.get",
            Self::ClientsRegisterPost => "clients.register.post",
            Self::CodeCapabilitiesGet => "code.capabilities.get",
            Self::CodeConventionsGet => "code.conventions.get",
            Self::CodeDefinitionGet => "code.definition.get",
            Self::CodeDiagnosticsGet => "code.diagnostics.get",
            Self::CodeHoverGet => "code.hover.get",
            Self::CodeLanguageMatrixGet => "code.language_matrix.get",
            Self::CodeLanguageRootGet => "code.language_root.get",
            Self::CodeLanguageSessionsGet => "code.language_sessions.get",
            Self::CodeLspGet => "code.lsp.get",
            Self::CodeRequestPost => "code.request.post",
            Self::CodeSymbolsGet => "code.symbols.get",
            Self::CodeWorkspaceDiagnosticsGet => "code.workspace_diagnostics.get",
            Self::CodeWorkspaceSymbolsGet => "code.workspace_symbols.get",
            Self::CodingEngineGet => "coding_engine.get",
            Self::ComponentsByComponentIdRuntimeEventsGet => "components.by_component_id.runtime.events.get",
            Self::ComponentsByComponentIdRuntimeEventsPost => "components.by_component_id.runtime.events.post",
            Self::ComponentsByComponentIdRuntimeProbeByProbeIdResultPost => "components.by_component_id.runtime.probe.by_probe_id.result.post",
            Self::ComponentsByComponentIdStoreByKeyDelete => "components.by_component_id.store.by_key.delete",
            Self::ComponentsByComponentIdStoreByKeyGet => "components.by_component_id.store.by_key.get",
            Self::ComponentsByComponentIdStoreByKeyPut => "components.by_component_id.store.by_key.put",
            Self::ComponentsByComponentIdStoreGet => "components.by_component_id.store.get",
            Self::ComponentsByComponentIdStoreKeysGet => "components.by_component_id.store.keys.get",
            Self::ComponentsByComponentIdStorePut => "components.by_component_id.store.put",
            Self::ContinuationsLineageByTurnCorrelationIdGet => "continuations.lineage.by_turn_correlation_id.get",
            Self::ContinuationsStatusGet => "continuations.status.get",
            Self::DeliverOutboxPost => "deliver.outbox.post",
            Self::DeliverPollByJobIdGet => "deliver.poll.by_job_id.get",
            Self::DeliveryStatusGet => "delivery.status.get",
            Self::EnvironmentSpecGet => "environment.spec.get",
            Self::EnvironmentSpecPendingApplyPost => "environment.spec.pending.apply.post",
            Self::EnvironmentSpecPendingDelete => "environment.spec.pending.delete",
            Self::EnvironmentSpecPendingGet => "environment.spec.pending.get",
            Self::EnvironmentSpecProposePost => "environment.spec.propose.post",
            Self::EnvironmentSpecPut => "environment.spec.put",
            Self::EnvironmentSpecStreamGet => "environment.spec.stream.get",
            Self::EnvironmentSpecValidatePost => "environment.spec.validate.post",
            Self::EnvironmentStatusGet => "environment.status.get",
            Self::FeedsByFeedIdLatestGoodGet => "feeds.by_feed_id.latest_good.get",
            Self::FeedsByFeedIdReadPost => "feeds.by_feed_id.read.post",
            Self::FeedsByFeedIdTailGet => "feeds.by_feed_id.tail.get",
            Self::FeedsGet => "feeds.get",
            Self::FeedsStreamGet => "feeds.stream.get",
            Self::ForgeEvidenceByEvidenceIdCommandsGet => "forge.evidence.by_evidence_id.commands.get",
            Self::ForgeEvidenceByEvidenceIdPatchGet => "forge.evidence.by_evidence_id.patch.get",
            Self::ForgeEvidenceByEvidenceIdReceiptsGet => "forge.evidence.by_evidence_id.receipts.get",
            Self::ForgeItemsByWorkIdApplyPost => "forge.items.by_work_id.apply.post",
            Self::ForgeItemsByWorkIdAttemptsPost => "forge.items.by_work_id.attempts.post",
            Self::ForgeItemsByWorkIdChangesBlameGet => "forge.items.by_work_id.changes.blame.get",
            Self::ForgeItemsByWorkIdChangesCheckpointPost => "forge.items.by_work_id.changes.checkpoint.post",
            Self::ForgeItemsByWorkIdChangesConflictPost => "forge.items.by_work_id.changes.conflict.post",
            Self::ForgeItemsByWorkIdChangesFetchPost => "forge.items.by_work_id.changes.fetch.post",
            Self::ForgeItemsByWorkIdChangesFileGet => "forge.items.by_work_id.changes.file.get",
            Self::ForgeItemsByWorkIdChangesFileHunkPost => "forge.items.by_work_id.changes.file.hunk.post",
            Self::ForgeItemsByWorkIdChangesFilePost => "forge.items.by_work_id.changes.file.post",
            Self::ForgeItemsByWorkIdChangesGet => "forge.items.by_work_id.changes.get",
            Self::ForgeItemsByWorkIdChangesHistoryGet => "forge.items.by_work_id.changes.history.get",
            Self::ForgeItemsByWorkIdChangesPullPost => "forge.items.by_work_id.changes.pull.post",
            Self::ForgeItemsByWorkIdChangesPushPost => "forge.items.by_work_id.changes.push.post",
            Self::ForgeItemsByWorkIdChangesSyncPost => "forge.items.by_work_id.changes.sync.post",
            Self::ForgeItemsByWorkIdDecisionsPost => "forge.items.by_work_id.decisions.post",
            Self::ForgeItemsByWorkIdDiscardPost => "forge.items.by_work_id.discard.post",
            Self::ForgeItemsByWorkIdExportPost => "forge.items.by_work_id.export.post",
            Self::ForgeItemsByWorkIdGet => "forge.items.by_work_id.get",
            Self::ForgeItemsByWorkIdHandoffPost => "forge.items.by_work_id.handoff.post",
            Self::ForgeItemsByWorkIdProjectEventsGet => "forge.items.by_work_id.project_events.get",
            Self::ForgeItemsByWorkIdProviderCommentsGet => "forge.items.by_work_id.provider.comments.get",
            Self::ForgeItemsByWorkIdProviderCommentsPost => "forge.items.by_work_id.provider.comments.post",
            Self::ForgeItemsByWorkIdProviderContextPut => "forge.items.by_work_id.provider.context.put",
            Self::ForgeItemsByWorkIdProviderGet => "forge.items.by_work_id.provider.get",
            Self::ForgeItemsByWorkIdProviderPost => "forge.items.by_work_id.provider.post",
            Self::ForgeItemsByWorkIdProvisionPost => "forge.items.by_work_id.provision.post",
            Self::ForgeItemsByWorkIdReviewCommentsByCommentIdDelete => "forge.items.by_work_id.review.comments.by_comment_id.delete",
            Self::ForgeItemsByWorkIdReviewCommentsByCommentIdPatch => "forge.items.by_work_id.review.comments.by_comment_id.patch",
            Self::ForgeItemsByWorkIdReviewCommentsGet => "forge.items.by_work_id.review.comments.get",
            Self::ForgeItemsByWorkIdReviewCommentsPost => "forge.items.by_work_id.review.comments.post",
            Self::ForgeItemsByWorkIdReviewContinueEditingPost => "forge.items.by_work_id.review.continue_editing.post",
            Self::ForgeItemsByWorkIdReviewFileGet => "forge.items.by_work_id.review.file.get",
            Self::ForgeItemsByWorkIdReviewFilePost => "forge.items.by_work_id.review.file.post",
            Self::ForgeItemsByWorkIdReviewGet => "forge.items.by_work_id.review.get",
            Self::ForgeItemsByWorkIdReviewRequestChangesPost => "forge.items.by_work_id.review.request_changes.post",
            Self::ForgeItemsByWorkIdRunScriptPost => "forge.items.by_work_id.run_script.post",
            Self::ForgeItemsByWorkIdSearchGet => "forge.items.by_work_id.search.get",
            Self::ForgeItemsByWorkIdSearchReplacePost => "forge.items.by_work_id.search.replace.post",
            Self::ForgeItemsByWorkIdSourceBatchPut => "forge.items.by_work_id.source.batch.put",
            Self::ForgeItemsByWorkIdSourceDelete => "forge.items.by_work_id.source.delete",
            Self::ForgeItemsByWorkIdSourceGet => "forge.items.by_work_id.source.get",
            Self::ForgeItemsByWorkIdSourcePatch => "forge.items.by_work_id.source.patch",
            Self::ForgeItemsByWorkIdSourcePost => "forge.items.by_work_id.source.post",
            Self::ForgeItemsByWorkIdSourcePut => "forge.items.by_work_id.source.put",
            Self::ForgeItemsByWorkIdSourceWorkspaceEditPut => "forge.items.by_work_id.source.workspace_edit.put",
            Self::ForgeItemsByWorkIdTaskRunsByRunIdDelete => "forge.items.by_work_id.task_runs.by_run_id.delete",
            Self::ForgeItemsByWorkIdTaskRunsByRunIdEventsGet => "forge.items.by_work_id.task_runs.by_run_id.events.get",
            Self::ForgeItemsByWorkIdTaskRunsByRunIdGet => "forge.items.by_work_id.task_runs.by_run_id.get",
            Self::ForgeItemsByWorkIdTaskRunsByRunIdPreviewPost => "forge.items.by_work_id.task_runs.by_run_id.preview.post",
            Self::ForgeItemsByWorkIdTaskRunsGet => "forge.items.by_work_id.task_runs.get",
            Self::ForgeItemsByWorkIdTasksByTaskIdRunPost => "forge.items.by_work_id.tasks.by_task_id.run.post",
            Self::ForgeItemsByWorkIdTasksByTaskIdRunsPost => "forge.items.by_work_id.tasks.by_task_id.runs.post",
            Self::ForgeItemsByWorkIdTasksGet => "forge.items.by_work_id.tasks.get",
            Self::ForgeItemsByWorkIdTestsGet => "forge.items.by_work_id.tests.get",
            Self::ForgeItemsByWorkIdTreeGet => "forge.items.by_work_id.tree.get",
            Self::ForgeItemsByWorkIdWorkspaceStateGet => "forge.items.by_work_id.workspace_state.get",
            Self::ForgeItemsByWorkIdWorkspaceStatePut => "forge.items.by_work_id.workspace_state.put",
            Self::ForgeItemsGet => "forge.items.get",
            Self::ForgeItemsPost => "forge.items.post",
            Self::ForgeItemsStartPost => "forge.items.start.post",
            Self::ForgeLeasesByLeaseIdCompletePost => "forge.leases.by_lease_id.complete.post",
            Self::ForgeLeasesByLeaseIdFailPost => "forge.leases.by_lease_id.fail.post",
            Self::ForgeLeasesByLeaseIdHeartbeatPost => "forge.leases.by_lease_id.heartbeat.post",
            Self::ForgeLeasesByLeaseIdInterruptPost => "forge.leases.by_lease_id.interrupt.post",
            Self::ForgePreviewByTokenByRestDelete => "forge.preview.by_token.by_rest.delete",
            Self::ForgePreviewByTokenByRestGet => "forge.preview.by_token.by_rest.get",
            Self::ForgePreviewByTokenByRestHead => "forge.preview.by_token.by_rest.head",
            Self::ForgePreviewByTokenByRestOptions => "forge.preview.by_token.by_rest.options",
            Self::ForgePreviewByTokenByRestPatch => "forge.preview.by_token.by_rest.patch",
            Self::ForgePreviewByTokenByRestPost => "forge.preview.by_token.by_rest.post",
            Self::ForgePreviewByTokenByRestPut => "forge.preview.by_token.by_rest.put",
            Self::ForgePreviewByTokenDelete => "forge.preview.by_token.delete",
            Self::ForgePreviewByTokenGet => "forge.preview.by_token.get",
            Self::ForgePreviewByTokenHead => "forge.preview.by_token.head",
            Self::ForgePreviewByTokenOptions => "forge.preview.by_token.options",
            Self::ForgePreviewByTokenPatch => "forge.preview.by_token.patch",
            Self::ForgePreviewByTokenPost => "forge.preview.by_token.post",
            Self::ForgePreviewByTokenPut => "forge.preview.by_token.put",
            Self::ForgeRepositoriesBrowseGet => "forge.repositories.browse.get",
            Self::ForgeRepositoriesGet => "forge.repositories.get",
            Self::ForgeRepositoriesInspectPost => "forge.repositories.inspect.post",
            Self::ForgeRepositoriesProviderGet => "forge.repositories.provider.get",
            Self::ForgeRepositoriesProviderPost => "forge.repositories.provider.post",
            Self::ForgeRepositoriesPut => "forge.repositories.put",
            Self::ForgeStreamGet => "forge.stream.get",
            Self::GraphemeAllowlistGet => "grapheme.allowlist.get",
            Self::GraphemeAllowlistPut => "grapheme.allowlist.put",
            Self::GraphemeCompilePost => "grapheme.compile.post",
            Self::GraphemeLifecycleGet => "grapheme.lifecycle.get",
            Self::GraphemeLspGet => "grapheme.lsp.get",
            Self::GraphemeLspWorkspaceGet => "grapheme.lsp.workspace.get",
            Self::GraphemeModulesByModuleIdGet => "grapheme.modules.by_module_id.get",
            Self::GraphemeModulesByModuleIdOpsGet => "grapheme.modules.by_module_id.ops.get",
            Self::GraphemeModulesGet => "grapheme.modules.get",
            Self::GraphemeModulesLoadPost => "grapheme.modules.load.post",
            Self::GraphemeRunPost => "grapheme.run.post",
            Self::GraphemeScriptsByScriptIdDelete => "grapheme.scripts.by_script_id.delete",
            Self::GraphemeScriptsByScriptIdGet => "grapheme.scripts.by_script_id.get",
            Self::GraphemeScriptsByScriptIdRenamePost => "grapheme.scripts.by_script_id.rename.post",
            Self::GraphemeScriptsGet => "grapheme.scripts.get",
            Self::GraphemeScriptsPost => "grapheme.scripts.post",
            Self::HealthGet => "health.get",
            Self::HeartbeatStatusGet => "heartbeat.status.get",
            Self::IdentityContextPost => "identity.context.post",
            Self::IdentityDigestPreviewPost => "identity.digest_preview.post",
            Self::IdentityExportMarkdownPost => "identity.export_markdown.post",
            Self::IdentityHistoryPost => "identity.history.post",
            Self::IdentityProfilesActivePut => "identity.profiles.active.put",
            Self::IdentityProfilesExportPost => "identity.profiles.export.post",
            Self::IdentityProfilesGet => "identity.profiles.get",
            Self::IdentityProfilesImportPost => "identity.profiles.import.post",
            Self::IdentityProfilesPost => "identity.profiles.post",
            Self::IdentityRememberPost => "identity.remember.post",
            Self::IdentityRollbackPost => "identity.rollback.post",
            Self::IdentityUpdateCommitPost => "identity.update.commit.post",
            Self::IdentityUpdateProposePost => "identity.update.propose.post",
            Self::IngestByStreamIdStreamGet => "ingest.by_stream_id.stream.get",
            Self::IngestPost => "ingest.post",
            Self::IntegrationsByConnectionIdDelete => "integrations.by_connection_id.delete",
            Self::IntegrationsByConnectionIdGet => "integrations.by_connection_id.get",
            Self::IntegrationsByConnectionIdPatch => "integrations.by_connection_id.patch",
            Self::IntegrationsByConnectionIdSecretsBySlotDelete => "integrations.by_connection_id.secrets.by_slot.delete",
            Self::IntegrationsByConnectionIdSecretsBySlotPut => "integrations.by_connection_id.secrets.by_slot.put",
            Self::IntegrationsGet => "integrations.get",
            Self::IntegrationsPost => "integrations.post",
            Self::InteractiveTurnByTurnIdStreamGet => "interactive.turn.by_turn_id.stream.get",
            Self::InteractiveTurnPost => "interactive.turn.post",
            Self::JobsAskPost => "jobs.ask.post",
            Self::JobsByJobIdArchivePost => "jobs.by_job_id.archive.post",
            Self::JobsByJobIdCompleteActionsPost => "jobs.by_job_id.complete_actions.post",
            Self::JobsByJobIdReplayAndResumePost => "jobs.by_job_id.replay_and_resume.post",
            Self::JobsByJobIdReportGet => "jobs.by_job_id.report.get",
            Self::JobsByJobIdResultGet => "jobs.by_job_id.result.get",
            Self::JobsPromptPost => "jobs.prompt.post",
            Self::JobsReportPost => "jobs.report.post",
            Self::LanWorkshopsGet => "lan.workshops.get",
            Self::LivenessGet => "liveness.get",
            Self::LocalCatalogGet => "local.catalog.get",
            Self::LocalEngineStatusGet => "local.engine.status.get",
            Self::LocalHardwareGet => "local.hardware.get",
            Self::LocalModelsByModelIdDelete => "local.models.by_model_id.delete",
            Self::LocalModelsDownloadByJobIdEventsGet => "local.models.download.by_job_id.events.get",
            Self::LocalModelsDownloadByJobIdGet => "local.models.download.by_job_id.get",
            Self::LocalModelsDownloadPost => "local.models.download.post",
            Self::LocalModelsGet => "local.models.get",
            Self::LocusNodesBySyncKeyGet => "locus.nodes.by_sync_key.get",
            Self::LocusNodesGet => "locus.nodes.get",
            Self::LocusTagsGet => "locus.tags.get",
            Self::MaintenanceArtifactsGet => "maintenance.artifacts.get",
            Self::MaintenanceArtifactsPut => "maintenance.artifacts.put",
            Self::MaintenanceStorageGet => "maintenance.storage.get",
            Self::MaintenanceStoragePost => "maintenance.storage.post",
            Self::MaintenanceStoragePut => "maintenance.storage.put",
            Self::ManuscriptsByManuscriptIdGet => "manuscripts.by_manuscript_id.get",
            Self::ManuscriptsByManuscriptIdPatch => "manuscripts.by_manuscript_id.patch",
            Self::ManuscriptsCreatePost => "manuscripts.create.post",
            Self::ManuscriptsGet => "manuscripts.get",
            Self::ManuscriptsPost => "manuscripts.post",
            Self::McpGatewayStatusGet => "mcp.gateway.status.get",
            Self::McpOauthBeginPost => "mcp.oauth.begin.post",
            Self::McpOauthByServerIdDelete => "mcp.oauth.by_server_id.delete",
            Self::McpOauthByServerIdGet => "mcp.oauth.by_server_id.get",
            Self::McpOauthCompletePost => "mcp.oauth.complete.post",
            Self::McpOauthRefreshPost => "mcp.oauth.refresh.post",
            Self::McpPolicyEvaluatePost => "mcp.policy.evaluate.post",
            Self::MediaByMediaIdGet => "media.by_media_id.get",
            Self::MediaUploadPost => "media.upload.post",
            Self::MeshInboxGet => "mesh.inbox.get",
            Self::MeshIntrosByIntroIdAcceptPost => "mesh.intros.by_intro_id.accept.post",
            Self::MeshIntrosByIntroIdDeclinePost => "mesh.intros.by_intro_id.decline.post",
            Self::MeshIntrosCandidatesGet => "mesh.intros.candidates.get",
            Self::MeshIntrosGet => "mesh.intros.get",
            Self::MeshIntrosPost => "mesh.intros.post",
            Self::MeshOutboxByItemIdFlushPost => "mesh.outbox.by_item_id.flush.post",
            Self::MeshOutboxGet => "mesh.outbox.get",
            Self::MeshOutboxPost => "mesh.outbox.post",
            Self::MeshPeersByDeviceIdPatch => "mesh.peers.by_device_id.patch",
            Self::MeshPeersGet => "mesh.peers.get",
            Self::MeshReceiptsGet => "mesh.receipts.get",
            Self::MeshReceiptsPost => "mesh.receipts.post",
            Self::MeshTasksByWorkIdControlPost => "mesh.tasks.by_work_id.control.post",
            Self::MeshTasksPost => "mesh.tasks.post",
            Self::ModelsCapabilitiesGet => "models.capabilities.get",
            Self::ModelsCatalogGet => "models.catalog.get",
            Self::ModelsCatalogRefreshPost => "models.catalog.refresh.post",
            Self::PairByPairingIdDelete => "pair.by_pairing_id.delete",
            Self::PairByPairingIdPolicyPut => "pair.by_pairing_id.policy.put",
            Self::PairCodeGet => "pair.code.get",
            Self::PairHeartbeatGet => "pair.heartbeat.get",
            Self::PairHeartbeatPost => "pair.heartbeat.post",
            Self::PairInitPost => "pair.init.post",
            Self::PairIrohTicketGet => "pair.iroh_ticket.get",
            Self::PairSessionChallengePost => "pair.session.challenge.post",
            Self::PairSessionRefreshPost => "pair.session.refresh.post",
            Self::PairStatusGet => "pair.status.get",
            Self::PairVerifyPost => "pair.verify.post",
            Self::PeerMessagesByMessageIdReadPost => "peer.messages.by_message_id.read.post",
            Self::PeerMessagesGet => "peer.messages.get",
            Self::PeerMessagesPost => "peer.messages.post",
            Self::PeerMessagesUnreadCountGet => "peer.messages.unread_count.get",
            Self::PeersByDeviceIdExecutionPolicyGet => "peers.by_device_id.execution_policy.get",
            Self::PeersByDeviceIdExecutionPolicyPut => "peers.by_device_id.execution_policy.put",
            Self::PeersExecutionPoliciesGet => "peers.execution_policies.get",
            Self::PeersExecutionPolicyAuditGet => "peers.execution_policy_audit.get",
            Self::PromptStashesByStashIdDelete => "prompt_stashes.by_stash_id.delete",
            Self::PromptStashesGet => "prompt_stashes.get",
            Self::PromptStashesPost => "prompt_stashes.post",
            Self::QrGet => "qr.get",
            Self::QrImageGet => "qr.image.get",
            Self::QrPngGet => "qr.png.get",
            Self::QrRotatePost => "qr.rotate.post",
            Self::RecurringByRecurringIdDelete => "recurring.by_recurring_id.delete",
            Self::RecurringByRecurringIdDeliveryGet => "recurring.by_recurring_id.delivery.get",
            Self::RecurringByRecurringIdPatch => "recurring.by_recurring_id.patch",
            Self::RecurringByRecurringIdRunsGet => "recurring.by_recurring_id.runs.get",
            Self::RecurringGet => "recurring.get",
            Self::RecurringPromptPost => "recurring.prompt.post",
            Self::RuntimeArtifactCommandPost => "runtime.artifact.command.post",
            Self::RuntimeArtifactDeletePost => "runtime.artifact.delete.post",
            Self::RuntimeArtifactFetchPost => "runtime.artifact.fetch.post",
            Self::RuntimeArtifactListUiPost => "runtime.artifact.list_ui.post",
            Self::RuntimeArtifactWritePost => "runtime.artifact.write.post",
            Self::RuntimeConfigCommandPost => "runtime.config.command.post",
            Self::RuntimeDefaultsGet => "runtime.defaults.get",
            Self::RuntimeInferenceProfilesPut => "runtime.inference_profiles.put",
            Self::RuntimeStageRouteCommandPost => "runtime.stage_route.command.post",
            Self::RuntimeTuiDefaultsGet => "runtime.tui_defaults.get",
            Self::RuntimeTuiDefaultsPut => "runtime.tui_defaults.put",
            Self::RuntimeWorkersGet => "runtime.workers.get",
            Self::RuntimeWorkersPut => "runtime.workers.put",
            Self::SessionDeletionsByDeletionIdGet => "session_deletions.by_deletion_id.get",
            Self::SessionsBySessionIdActiveTurnGet => "sessions.by_session_id.active_turn.get",
            Self::SessionsBySessionIdActiveTurnPost => "sessions.by_session_id.active_turn.post",
            Self::SessionsBySessionIdAgentModeDelete => "sessions.by_session_id.agent_mode.delete",
            Self::SessionsBySessionIdAgentModeGet => "sessions.by_session_id.agent_mode.get",
            Self::SessionsBySessionIdAgentModeProposalsByProposalIdPut => "sessions.by_session_id.agent_mode.proposals.by_proposal_id.put",
            Self::SessionsBySessionIdAgentModeProposalsGet => "sessions.by_session_id.agent_mode.proposals.get",
            Self::SessionsBySessionIdAgentModePut => "sessions.by_session_id.agent_mode.put",
            Self::SessionsBySessionIdBotDelete => "sessions.by_session_id.bot.delete",
            Self::SessionsBySessionIdBotGet => "sessions.by_session_id.bot.get",
            Self::SessionsBySessionIdBotPut => "sessions.by_session_id.bot.put",
            Self::SessionsBySessionIdCodeBindingDelete => "sessions.by_session_id.code_binding.delete",
            Self::SessionsBySessionIdCodeBindingGet => "sessions.by_session_id.code_binding.get",
            Self::SessionsBySessionIdCodeBindingPut => "sessions.by_session_id.code_binding.put",
            Self::SessionsBySessionIdCodeProjectPost => "sessions.by_session_id.code_project.post",
            Self::SessionsBySessionIdDelete => "sessions.by_session_id.delete",
            Self::SessionsBySessionIdHistoryGet => "sessions.by_session_id.history.get",
            Self::SessionsBySessionIdNamePut => "sessions.by_session_id.name.put",
            Self::SessionsBySessionIdTurnsGet => "sessions.by_session_id.turns.get",
            Self::SessionsBySessionIdTurnsPost => "sessions.by_session_id.turns.post",
            Self::SessionsBySessionIdWorkshopSteerPost => "sessions.by_session_id.workshop.steer.post",
            Self::SessionsDerivePost => "sessions.derive.post",
            Self::SessionsGet => "sessions.get",
            Self::SessionsPost => "sessions.post",
            Self::SessionsSearchGet => "sessions.search.get",
            Self::SessionsShellByIdGet => "sessions.shell.by_id.get",
            Self::SessionsShellByIdSignalPost => "sessions.shell.by_id.signal.post",
            Self::SessionsShellGet => "sessions.shell.get",
            Self::SessionsShellPost => "sessions.shell.post",
            Self::ShareCapabilitiesGet => "share.capabilities.get",
            Self::ShareExportPost => "share.export.post",
            Self::ShareImportPost => "share.import.post",
            Self::SharePushPost => "share.push.post",
            Self::SharedModeGet => "shared_mode.get",
            Self::SharedModePut => "shared_mode.put",
            Self::ShellSessionsGet => "shell_sessions.get",
            Self::StatsGet => "stats.get",
            Self::SttStatusGet => "stt.status.get",
            Self::SttTranscribePost => "stt.transcribe.post",
            Self::ToolHistorySlicesGet => "tool_history.slices.get",
            Self::TurnsBudgetRequestsByRequestIdApprovePost => "turns.budget_requests.by_request_id.approve.post",
            Self::TurnsBudgetRequestsByRequestIdDenyPost => "turns.budget_requests.by_request_id.deny.post",
            Self::TurnsBudgetRequestsByRequestIdGet => "turns.budget_requests.by_request_id.get",
            Self::TurnsBudgetRequestsGet => "turns.budget_requests.get",
            Self::TurnsByTurnIdGet => "turns.by_turn_id.get",
            Self::TurnsPost => "turns.post",
            Self::VaultActivePut => "vault.active.put",
            Self::VaultBacklinksGet => "vault.backlinks.get",
            Self::VaultChangesGet => "vault.changes.get",
            Self::VaultFilesByFilePathGet => "vault.files.by_file_path.get",
            Self::VaultGitCommitPost => "vault.git.commit.post",
            Self::VaultGitDetectGet => "vault.git.detect.get",
            Self::VaultGitDiffGet => "vault.git.diff.get",
            Self::VaultGitEnablePost => "vault.git.enable.post",
            Self::VaultGitInitPost => "vault.git.init.post",
            Self::VaultGitInstallPost => "vault.git.install.post",
            Self::VaultGitLogGet => "vault.git.log.get",
            Self::VaultGitRestorePost => "vault.git.restore.post",
            Self::VaultGitStatusGet => "vault.git.status.get",
            Self::VaultGitWorktreesGet => "vault.git.worktrees.get",
            Self::VaultNotesByNotePathDelete => "vault.notes.by_note_path.delete",
            Self::VaultNotesByNotePathGet => "vault.notes.by_note_path.get",
            Self::VaultNotesByNotePathPut => "vault.notes.by_note_path.put",
            Self::VaultNotesGet => "vault.notes.get",
            Self::VaultNotesPost => "vault.notes.post",
            Self::VaultRootsGet => "vault.roots.get",
            Self::VaultRootsPost => "vault.roots.post",
            Self::VaultSearchGet => "vault.search.get",
            Self::VaultTagsGet => "vault.tags.get",
            Self::VaultTrashGet => "vault.trash.get",
            Self::VaultTrashRestorePost => "vault.trash.restore.post",
            Self::WorkflowsByWorkflowIdGet => "workflows.by_workflow_id.get",
            Self::WorkflowsByWorkflowIdRunsGet => "workflows.by_workflow_id.runs.get",
            Self::WorkflowsFromSlicePost => "workflows.from_slice.post",
            Self::WorkflowsGet => "workflows.get",
            Self::WorkflowsPlanPost => "workflows.plan.post",
            Self::WorkflowsPost => "workflows.post",
            Self::WorkflowsSchedulePost => "workflows.schedule.post",
            Self::WorkspaceCardsByCardIdArchivePost => "workspace.cards.by_card_id.archive.post",
            Self::WorkspaceCardsByCardIdCancelPost => "workspace.cards.by_card_id.cancel.post",
            Self::WorkspaceCardsByCardIdGet => "workspace.cards.by_card_id.get",
            Self::WorkspaceCardsByCardIdLinkVaultPost => "workspace.cards.by_card_id.link_vault.post",
            Self::WorkspaceCardsByCardIdRetryPost => "workspace.cards.by_card_id.retry.post",
            Self::WorkspaceCardsGet => "workspace.cards.get",
            Self::WorkspaceFeedGet => "workspace.feed.get",
            Self::WorkspaceRebuildPost => "workspace.rebuild.post",
            Self::WorkspaceSnapshotGet => "workspace.snapshot.get",
            Self::WorkspaceStreamGet => "workspace.stream.get",
            Self::WorldAtLocationGet => "world.at_location.get",
            Self::WorldBindingsByWorkIdGet => "world.bindings.by_work_id.get",
            Self::WorldCodeAvecGet => "world.code_avec.get",
            Self::WorldFilesGet => "world.files.get",
            Self::WorldFindGet => "world.find.get",
            Self::WorldGet => "world.get",
            Self::WorldImpactGet => "world.impact.get",
            Self::WorldIndexPost => "world.index.post",
            Self::WorldResetStorePost => "world.reset_store.post",
            Self::WorldStatusGet => "world.status.get",
        }
    }
}
