#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

check_only=0
snapshot_path=""
compare_path=""

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --check)
            check_only=1
            ;;
        --snapshot|--record)
            if [[ "$#" -lt 2 ]]; then
                printf '%s\n' "Missing path for $1" >&2
                exit 2
            fi
            snapshot_path="$2"
            shift
            ;;
        --compare)
            if [[ "$#" -lt 2 ]]; then
                printf '%s\n' "Missing path for --compare" >&2
                exit 2
            fi
            compare_path="$2"
            shift
            ;;
        --help)
            printf '%s\n' "Usage: scripts/audit-semantic-typing.sh [--check] [--snapshot PATH] [--compare PATH]"
            exit 0
            ;;
        *)
            printf '%s\n' "Unknown option: $1" >&2
            exit 2
            ;;
    esac
    shift
done

count_matches() {
    local pattern="$1"
    shift
    local matches
    matches="$(rg -o --no-messages "$pattern" "$@" || true)"
    if [[ -z "$matches" ]]; then
        printf '0\n'
    else
        printf '%s\n' "$matches" | wc -l | tr -d ' '
    fi
}

collect_snapshot() {
    printf 'trim_calls=%s\n' "$(count_matches 'trim\(\)' src)"
    printf 'lenient_compatibility_helpers=%s\n' "$(count_matches 'deserialize_lenient_' src)"
    printf 'direct_port_failure_string_mappings=%s\n' "$(count_matches 'PortFailure\([^)]*to_string' src)"
    printf 'runtime_composition_backend_mentions=%s\n' "$(count_matches 'RuntimeComposition::(InMemory|Surreal)' src)"
    printf 'new_job_literals=%s\n' "$(count_matches 'NewJob[[:space:]]*\{' src)"
    printf 'recurring_definition_literals=%s\n' "$(count_matches 'RecurringDefinition[[:space:]]*\{' src)"
    printf 'channel_delivery_target_literals=%s\n' "$(count_matches 'ChannelDeliveryTarget[[:space:]]*\{' src)"
    printf 'too_many_arguments_allowances=%s\n' "$(count_matches 'allow\(clippy::too_many_arguments\)' src)"
}

snapshot_value() {
    local snapshot="$1"
    local key="$2"
    printf '%s\n' "$snapshot" | awk -F= -v key="$key" '$1 == key { print $2 }'
}

snapshot="$(collect_snapshot)"

printf '%s\n' "Semantic typing audit (source baseline)"
printf '%-42s %s\n' "trim calls" "$(snapshot_value "$snapshot" trim_calls)"
printf '%-42s %s\n' "lenient compatibility helpers" "$(snapshot_value "$snapshot" lenient_compatibility_helpers)"
printf '%-42s %s\n' "direct PortFailure string mappings" "$(snapshot_value "$snapshot" direct_port_failure_string_mappings)"
printf '%-42s %s\n' "RuntimeComposition backend mentions" "$(snapshot_value "$snapshot" runtime_composition_backend_mentions)"
printf '%-42s %s\n' "NewJob literals" "$(snapshot_value "$snapshot" new_job_literals)"
printf '%-42s %s\n' "RecurringDefinition literals" "$(snapshot_value "$snapshot" recurring_definition_literals)"
printf '%-42s %s\n' "ChannelDeliveryTarget literals" "$(snapshot_value "$snapshot" channel_delivery_target_literals)"
printf '%-42s %s\n' "too_many_arguments allowances" "$(snapshot_value "$snapshot" too_many_arguments_allowances)"

recurring_paths=(
    src/recurring_delivery.rs
    src/recurring_feed.rs
)

printf '%s\n' ""
printf '%s\n' "Migrated recurring JSON boundary"
printf '%s\n' "Allowed legacy adapter reparsing (serde_json::from_value):"
if ! rg -n --no-heading 'serde_json::from_value' "${recurring_paths[@]}"; then
    printf '%s\n' "(none)"
fi

check_failed=0
if rg -n --no-heading 'serde_json::to_value' "${recurring_paths[@]}"; then
    printf '%s\n' "FAIL: typed recurring paths must not serialize values for internal reparsing" >&2
    check_failed=1
else
    printf '%s\n' "PASS: no typed recurring serialization round trip detected"
fi

if [[ -n "$snapshot_path" ]]; then
    {
        printf '%s\n' "# Semantic typing audit snapshot"
        printf '%s\n' "# Generated by scripts/audit-semantic-typing.sh"
        printf '%s\n' "$snapshot"
    } > "$snapshot_path"
    printf '%s\n' "Wrote audit snapshot: $snapshot_path"
fi

if [[ -n "$compare_path" ]]; then
    if [[ ! -f "$compare_path" ]]; then
        printf '%s\n' "Missing audit snapshot: $compare_path" >&2
        exit 2
    fi
    printf '%s\n' ""
    printf '%s\n' "Semantic typing audit comparison (snapshot -> current)"
    comparison_failed=0
    while IFS='=' read -r key expected; do
        if [[ -z "$key" || "$key" == \#* ]]; then
            continue
        fi
        actual="$(snapshot_value "$snapshot" "$key")"
        if [[ -z "$actual" ]]; then
            printf '%s\n' "Missing current metric: $key" >&2
            comparison_failed=1
            continue
        fi
        delta=$((actual - expected))
        printf '%-42s %s -> %s (%+d)\n' "$key" "$expected" "$actual" "$delta"
    done < "$compare_path"
    if [[ "$comparison_failed" -ne 0 ]]; then
        exit 2
    fi
fi

if [[ "$check_only" -eq 1 && "$check_failed" -ne 0 ]]; then
    exit 1
fi
