#!/usr/bin/env python3
"""Generate TypeScript interfaces from sdk-contract/medousa-types.schema.json for Medousa Home."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "sdk-contract" / "medousa-types.schema.json"
OUT = ROOT / "apps" / "medousa-home" / "src" / "lib" / "types" / "generated" / "daemon_api.ts"

# Stream + session types Home relies on for SSE replay contract parity.
HOME_TYPES = [
    "InteractiveTurnStreamEvent",
    "InteractiveTurnResponse",
    "InteractiveTurnRequest",
    "TurnTicketRecord",
]


def ts_type(schema: dict, defs: dict) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return ref

    t = schema.get("type")
    if t == "string":
        if schema.get("format") == "date-time":
            return "string"
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        inner = ts_type(schema.get("items", {}), defs)
        return f"{inner}[]"
    if t == "object":
        return "Record<string, unknown>"

    if "anyOf" in schema or "oneOf" in schema:
        parts = schema.get("anyOf") or schema.get("oneOf") or []
        return " | ".join(ts_type(part, defs) for part in parts)

    return "unknown"


def emit_interface(name: str, schema_root: dict, defs: dict) -> list[str]:
    schema = schema_root.get("schema", schema_root)
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]

    for prop, prop_schema in props.items():
        optional = "" if prop in required else "?"
        ts_name = prop
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", prop):
            ts_name = json.dumps(prop)
        ty = ts_type(prop_schema, defs)
        if prop not in required and prop_schema.get("default") is not None:
            lines.append(f"  {ts_name}{optional}: {ty};")
        else:
            lines.append(f"  {ts_name}{optional}: {ty};")

    lines.append("}")
    return lines


def main() -> int:
    if not SCHEMA.exists():
        print(f"Missing {SCHEMA}; run: cargo run -p medousa-types-schema", file=sys.stderr)
        return 1

    schemas: dict = json.loads(SCHEMA.read_text())
    defs = schemas

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body: list[str] = [
        "// DO NOT EDIT — generated by scripts/gen-ts-types.py",
        "// Source: sdk-contract/medousa-types.schema.json",
        "",
    ]

    for name in HOME_TYPES:
        if name not in schemas:
            print(f"warn: {name} missing from schema", file=sys.stderr)
            continue
        body.extend(emit_interface(name, schemas[name], defs))
        body.append("")

    OUT.write_text("\n".join(body).rstrip() + "\n")
    print(f"Generated {OUT} ({len(HOME_TYPES)} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
