#!/usr/bin/env python3
"""Generate Pydantic models from sdk-contract/medousa-types.schema.json."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "sdk-contract" / "medousa-types.schema.json"
OUT_DIR = ROOT / "python" / "medousa-sdk" / "src" / "medousa" / "types" / "_generated"
OUT_FILE = OUT_DIR / "models.py"


def main() -> int:
    if not SCHEMA.exists():
        print(f"Run: cargo run -p medousa-types-schema\nMissing {SCHEMA}", file=sys.stderr)
        return 1

    schemas: dict = json.loads(SCHEMA.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # OpenAPI-style wrapper so datamodel-code-generator ingests all definitions
    openapi = {
        "openapi": "3.0.0",
        "info": {"title": "medousa-types", "version": "1.0.0"},
        "paths": {},
        "components": {"schemas": {}},
    }
    for name, root in schemas.items():
        openapi["components"]["schemas"][name] = root.get("schema", root)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as tmp:
        json.dump(openapi, tmp)
        tmp_path = tmp.name

    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                tmp_path,
                "--input-file-type",
                "openapi",
                "--output",
                str(OUT_FILE),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--use-standard-collections",
                "--use-union-operator",
                "--field-constraints",
                "--use-default",
                "--target-python-version",
                "3.10",
                "--disable-timestamp",
            ],
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("datamodel-code-generator failed; writing minimal fallback", file=sys.stderr)
        _write_fallback(schemas)
    finally:
        Path(tmp_path).unlink(missing_ok=True)

    header = '''\
# DO NOT EDIT — generated by scripts/gen-python-types.py
# Source: sdk-contract/medousa-types.schema.json (cargo run -p medousa-types-schema)

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

class MedousaModel(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

'''
    body = OUT_FILE.read_text()
    if "class MedousaModel" not in body:
        body = body.replace(
            "from pydantic import BaseModel",
            "from pydantic import BaseModel, ConfigDict, Field",
        )
        body = body.replace("class ", "class ", 1)
        # Replace BaseModel with MedousaModel for generated classes
        lines = []
        for line in body.splitlines():
            if line.startswith("class ") and "(BaseModel)" in line:
                line = line.replace("(BaseModel)", "(MedousaModel)")
            lines.append(line)
        body = header + "\n".join(lines[lines[0].startswith("#") and 0 or 0 :])
    else:
        if not body.startswith("# DO NOT EDIT"):
            body = header + body

    OUT_FILE.write_text(body)
    init = OUT_DIR / "__init__.py"
    init.write_text('"""Auto-generated medousa-types mirrors."""\nfrom medousa.types._generated.models import *  # noqa: F403\n')
    print(f"Generated {OUT_FILE} ({len(schemas)} types)")
    return 0


def _write_fallback(schemas: dict) -> None:
    """Minimal generator when datamodel-code-generator is unavailable."""
    lines = [
        "# DO NOT EDIT — generated by scripts/gen-python-types.py (fallback)",
        "from __future__ import annotations",
        "from datetime import datetime",
        "from typing import Any",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "class MedousaModel(BaseModel):",
        "    model_config = ConfigDict(extra='ignore', populate_by_name=True)",
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"class {name}(MedousaModel):")
        lines.append("    model_config = ConfigDict(extra='allow', populate_by_name=True)")
        lines.append("")
    OUT_FILE.write_text("\n".join(lines))


if __name__ == "__main__":
    raise SystemExit(main())
