#!/usr/bin/env python3
"""Generate TypeScript interfaces from sdk-contract/medousa-types.schema.json for Medousa Home."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "sdk-contract" / "medousa-types.schema.json"
OUT = ROOT / "apps" / "medousa-home" / "src" / "lib" / "types" / "generated" / "daemon_api.ts"

# Stream + session types Home relies on for SSE replay contract parity.
# Nested $ref targets (MediaRef, ContextUsageReport, …) are resolved automatically.
HOME_TYPES = [
    "InteractiveTurnStreamEvent",
    "InteractiveTurnResponse",
    "InteractiveTurnRequest",
    "TurnTicketRecord",
]


def find_schema(name: str, schemas: dict) -> dict | None:
    if name in schemas and isinstance(schemas[name], dict):
        return schemas[name]
    for root in schemas.values():
        if not isinstance(root, dict):
            continue
        defs = root.get("definitions")
        if isinstance(defs, dict) and name in defs and isinstance(defs[name], dict):
            return defs[name]
    return None


def collect_refs(schema: dict, found: set[str]) -> None:
    if not isinstance(schema, dict):
        return
    if "$ref" in schema:
        found.add(schema["$ref"].split("/")[-1])
        return
    for key in ("anyOf", "oneOf", "allOf"):
        for part in schema.get(key) or []:
            collect_refs(part, found)
    if "items" in schema:
        collect_refs(schema["items"], found)
    for prop in (schema.get("properties") or {}).values():
        collect_refs(prop, found)
    if "additionalProperties" in schema and isinstance(schema["additionalProperties"], dict):
        collect_refs(schema["additionalProperties"], found)


def ts_type(schema: dict, defs: dict) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return ref

    t = schema.get("type")
    if isinstance(t, list):
        parts = [ts_type({**schema, "type": item}, defs) for item in t if item != "null"]
        if "null" in t:
            if not parts:
                return "null"
            inner = " | ".join(parts)
            return f"{inner} | null"
        return " | ".join(parts) if parts else "unknown"

    if t == "string":
        if schema.get("format") == "date-time":
            return "string"
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        items = schema.get("items", {})
        if items is True or items == {}:
            return "unknown[]"
        inner = ts_type(items, defs)
        return f"{inner}[]"
    if t == "object":
        return "Record<string, unknown>"

    if "anyOf" in schema or "oneOf" in schema:
        parts = schema.get("anyOf") or schema.get("oneOf") or []
        mapped = []
        for part in parts:
            if part.get("type") == "null":
                mapped.append("null")
            else:
                mapped.append(ts_type(part, defs))
        # Deduplicate while preserving order
        seen: set[str] = set()
        uniq = []
        for part in mapped:
            if part not in seen:
                seen.add(part)
                uniq.append(part)
        return " | ".join(uniq) if uniq else "unknown"

    return "unknown"


def emit_interface(name: str, schema_root: dict, defs: dict) -> list[str]:
    schema = schema_root.get("schema", schema_root)
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]

    for prop, prop_schema in props.items():
        optional = "" if prop in required else "?"
        ts_name = prop
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", prop):
            ts_name = json.dumps(prop)
        ty = ts_type(prop_schema, defs)
        lines.append(f"  {ts_name}{optional}: {ty};")

    lines.append("}")
    return lines


def main() -> int:
    if not SCHEMA.exists():
        print(f"Missing {SCHEMA}; run: cargo run -p medousa-types-schema", file=sys.stderr)
        return 1

    schemas: dict = json.loads(SCHEMA.read_text())
    defs = schemas

    needed: list[str] = []
    seen: set[str] = set()

    def enqueue(name: str) -> None:
        if name in seen:
            return
        seen.add(name)
        schema = find_schema(name, schemas)
        if schema is None:
            print(f"warn: {name} missing from schema", file=sys.stderr)
            return
        refs: set[str] = set()
        collect_refs(schema, refs)
        for ref in sorted(refs):
            enqueue(ref)
        needed.append(name)

    for name in HOME_TYPES:
        enqueue(name)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body: list[str] = [
        "// DO NOT EDIT — generated by scripts/gen-ts-types.py",
        "// Source: sdk-contract/medousa-types.schema.json",
        "",
    ]

    for name in needed:
        schema = find_schema(name, schemas)
        if schema is None:
            continue
        body.extend(emit_interface(name, schema, defs))
        body.append("")

    OUT.write_text("\n".join(body).rstrip() + "\n")
    print(f"Generated {OUT} ({len(needed)} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
