#!/usr/bin/env python3
"""Generate Pydantic models from sdk-contract/medousa-types.schema.json."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "sdk-contract" / "medousa-types.schema.json"
OUT_DIR = ROOT / "python" / "medousa-sdk" / "src" / "medousa" / "types" / "_generated"
OUT_FILE = OUT_DIR / "models.py"


def main() -> int:
    if not SCHEMA.exists():
        print(f"Run: cargo run -p medousa-types-schema\nMissing {SCHEMA}", file=sys.stderr)
        return 1

    schemas: dict = json.loads(SCHEMA.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # OpenAPI-style wrapper so datamodel-code-generator ingests all definitions
    openapi = {
        "openapi": "3.0.0",
        "info": {"title": "medousa-types", "version": "1.0.0"},
        "paths": {},
        "components": {"schemas": {}},
    }
    for name, root in schemas.items():
        openapi["components"]["schemas"][name] = root.get("schema", root)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as tmp:
        json.dump(openapi, tmp)
        tmp_path = tmp.name

    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                tmp_path,
                "--input-file-type",
                "openapi",
                "--output",
                str(OUT_FILE),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--use-standard-collections",
                "--use-union-operator",
                "--field-constraints",
                "--use-default",
                "--target-python-version",
                "3.10",
                "--disable-timestamp",
            ],
            check=True,
        )
        _normalize_generated(schemas)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("datamodel-code-generator failed; writing minimal fallback", file=sys.stderr)
        _write_fallback(schemas)
    finally:
        Path(tmp_path).unlink(missing_ok=True)

    init = OUT_DIR / "__init__.py"
    init.write_text(
        '"""Auto-generated medousa-types mirrors."""\n'
        "from medousa.types._generated.models import *  # noqa: F403\n"
    )
    print(f"Generated {OUT_FILE} ({len(schemas)} types)")
    return 0


def _normalize_generated(schemas: dict) -> None:
    """Rewrite codegen output into a deterministic, ruff-clean module."""
    raw = OUT_FILE.read_text()
    class_lines: list[str] = []
    needs_any = "Any" in raw
    needs_aware = "AwareDatetime" in raw
    needs_root = "RootModel" in raw
    needs_field = "Field(" in raw

    in_class = False
    for line in raw.splitlines():
        if line.startswith("class "):
            in_class = True
            line = line.replace("(BaseModel)", "(MedousaModel)")
        if not in_class:
            continue
        class_lines.append(line)

    if not class_lines:
        _write_fallback(schemas)
        return

    pydantic_imports = ["BaseModel", "ConfigDict"]
    if needs_field:
        pydantic_imports.append("Field")
    if needs_aware:
        pydantic_imports.append("AwareDatetime")
    if needs_root:
        pydantic_imports.append("RootModel")
    # Stable alphabetical order for ruff/isort.
    pydantic_imports = sorted(set(pydantic_imports))

    lines = [
        "# DO NOT EDIT — generated by scripts/gen-python-types.py",
        "# Source: sdk-contract/medousa-types.schema.json (cargo run -p medousa-types-schema)",
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_any:
        lines.append("from typing import Any")
        lines.append("")
    lines.append(f"from pydantic import {', '.join(pydantic_imports)}")
    lines.extend(
        [
            "",
            "",
            "class MedousaModel(BaseModel):",
            '    model_config = ConfigDict(extra="ignore", populate_by_name=True)',
            "",
            "",
        ]
    )
    lines.extend(class_lines)
    OUT_FILE.write_text("\n".join(lines).rstrip() + "\n")


def _write_fallback(schemas: dict) -> None:
    """Minimal generator when datamodel-code-generator is unavailable."""
    lines = [
        "# DO NOT EDIT — generated by scripts/gen-python-types.py (fallback)",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, ConfigDict",
        "",
        "",
        "class MedousaModel(BaseModel):",
        '    model_config = ConfigDict(extra="ignore", populate_by_name=True)',
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"class {name}(MedousaModel):")
        lines.append("    model_config = ConfigDict(extra='allow', populate_by_name=True)")
        lines.append("")
    OUT_FILE.write_text("\n".join(lines))


if __name__ == "__main__":
    raise SystemExit(main())
